import { FormularyItem } from './medicationTypes'

// =============================================================================
// Sevaro Clinical - Neurology Formulary
// ~70 common neurology medications organized by category for typeahead search
// =============================================================================

export const NEURO_FORMULARY: FormularyItem[] = [
  // ---------------------------------------------------------------------------
  // Headache / Migraine (~15)
  // ---------------------------------------------------------------------------
  {
    name: 'Imitrex',
    generic_name: 'sumatriptan',
    category: 'Headache/Migraine',
    common_dosages: ['25 mg', '50 mg', '100 mg', '6 mg/0.5 mL injection', '5 mg nasal', '20 mg nasal'],
    routes: ['oral', 'subcutaneous', 'intranasal'],
    common_frequencies: ['PRN (max 200 mg/day oral)', 'PRN (max 12 mg/day SC)'],
    interactions_note: 'Contraindicated with MAOIs and ergotamines. Avoid within 24 hours of other triptans.',
  },
  {
    name: 'Maxalt',
    generic_name: 'rizatriptan',
    category: 'Headache/Migraine',
    common_dosages: ['5 mg', '10 mg'],
    routes: ['oral', 'oral disintegrating tablet'],
    common_frequencies: ['PRN (max 30 mg/day)'],
    interactions_note: 'Reduce dose to 5 mg with propranolol. Contraindicated with MAOIs.',
  },
  {
    name: 'Topamax',
    generic_name: 'topiramate',
    category: 'Headache/Migraine',
    common_dosages: ['25 mg', '50 mg', '100 mg', '200 mg'],
    routes: ['oral'],
    common_frequencies: ['BID'],
    monitoring: 'Serum bicarbonate, renal function, intraocular pressure. Monitor for cognitive side effects and weight loss.',
    interactions_note: 'Reduces efficacy of oral contraceptives. Increases risk of kidney stones.',
  },
  {
    name: 'Depakote',
    generic_name: 'valproic acid',
    category: 'Headache/Migraine',
    common_dosages: ['250 mg', '500 mg', '500 mg ER', '1000 mg ER'],
    routes: ['oral'],
    common_frequencies: ['BID', 'Daily (ER formulation)'],
    monitoring: 'LFTs at baseline and periodically. CBC with platelets. Valproic acid level (target 50-100 mcg/mL for epilepsy). Ammonia if encephalopathy suspected.',
    interactions_note: 'Teratogenic - contraindicated in pregnancy. Interacts with lamotrigine (doubles lamotrigine levels). Hepatotoxicity risk.',
  },
  {
    name: 'Elavil',
    generic_name: 'amitriptyline',
    category: 'Headache/Migraine',
    common_dosages: ['10 mg', '25 mg', '50 mg', '75 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS'],
    monitoring: 'ECG at baseline for patients >40 years or with cardiac history.',
    interactions_note: 'Anticholinergic effects. Avoid with MAOIs. QTc prolongation risk. Sedation common - give at bedtime.',
  },
  {
    name: 'Inderal',
    generic_name: 'propranolol',
    category: 'Headache/Migraine',
    common_dosages: ['20 mg', '40 mg', '60 mg', '80 mg', '60 mg LA', '80 mg LA', '120 mg LA', '160 mg LA'],
    routes: ['oral'],
    common_frequencies: ['BID (IR)', 'Daily (LA)'],
    monitoring: 'Heart rate, blood pressure.',
    interactions_note: 'Increases rizatriptan levels - reduce rizatriptan dose. Avoid abrupt discontinuation. Caution in asthma/COPD and diabetes.',
  },
  {
    name: 'Calan',
    generic_name: 'verapamil',
    category: 'Headache/Migraine',
    common_dosages: ['80 mg', '120 mg', '240 mg', '120 mg SR', '240 mg SR', '360 mg SR'],
    routes: ['oral'],
    common_frequencies: ['TID (IR)', 'BID (SR)', 'Daily (SR)'],
    monitoring: 'ECG at baseline and with dose increases (PR interval). Heart rate, blood pressure.',
    interactions_note: 'Avoid with beta-blockers (risk of heart block). Inhibits CYP3A4.',
  },
  {
    name: 'Emgality',
    generic_name: 'galcanezumab-gnlm',
    category: 'Headache/Migraine',
    common_dosages: ['120 mg/mL prefilled syringe', '240 mg loading dose (2 injections)', '300 mg/mL (cluster headache)'],
    routes: ['subcutaneous'],
    common_frequencies: ['Monthly (migraine)', 'Monthly (cluster headache - 300 mg)'],
    monitoring: 'Monitor for injection site reactions and hypersensitivity.',
    interactions_note: 'CGRP monoclonal antibody. No significant drug interactions. Avoid in pregnancy.',
  },
  {
    name: 'Aimovig',
    generic_name: 'erenumab-aooe',
    category: 'Headache/Migraine',
    common_dosages: ['70 mg/mL prefilled syringe', '140 mg/mL prefilled syringe'],
    routes: ['subcutaneous'],
    common_frequencies: ['Monthly'],
    monitoring: 'Monitor for constipation (common), hypertension, injection site reactions.',
    interactions_note: 'CGRP receptor antagonist. May cause or worsen constipation and hypertension.',
  },
  {
    name: 'Ajovy',
    generic_name: 'fremanezumab-vfrm',
    category: 'Headache/Migraine',
    common_dosages: ['225 mg/1.5 mL prefilled syringe', '675 mg (3 injections quarterly)'],
    routes: ['subcutaneous'],
    common_frequencies: ['Monthly (225 mg)', 'Quarterly (675 mg)'],
    monitoring: 'Monitor for injection site reactions and hypersensitivity.',
    interactions_note: 'CGRP monoclonal antibody. No significant drug interactions.',
  },
  {
    name: 'Vyepti',
    generic_name: 'eptinezumab-jjmr',
    category: 'Headache/Migraine',
    common_dosages: ['100 mg/mL IV infusion', '300 mg IV infusion'],
    routes: ['intravenous'],
    common_frequencies: ['Every 3 months'],
    monitoring: 'Monitor during infusion for hypersensitivity/anaphylaxis.',
    interactions_note: 'CGRP monoclonal antibody. Administer as 30-minute IV infusion.',
  },
  {
    name: 'Reyvow',
    generic_name: 'lasmiditan',
    category: 'Headache/Migraine',
    common_dosages: ['50 mg', '100 mg'],
    routes: ['oral'],
    common_frequencies: ['PRN (max 1 dose/day)'],
    interactions_note: 'Schedule V controlled substance. Do not drive within 8 hours of dosing. Serotonin syndrome risk with SSRIs/SNRIs.',
  },
  {
    name: 'Ubrelvy',
    generic_name: 'ubrogepant',
    category: 'Headache/Migraine',
    common_dosages: ['50 mg', '100 mg'],
    routes: ['oral'],
    common_frequencies: ['PRN (may repeat once after 2 hours, max 200 mg/day)'],
    interactions_note: 'CGRP receptor antagonist (oral gepant). Avoid with strong CYP3A4 inhibitors. Dose adjustment with moderate CYP3A4 inhibitors.',
  },
  {
    name: 'Nurtec ODT',
    generic_name: 'rimegepant',
    category: 'Headache/Migraine',
    common_dosages: ['75 mg ODT'],
    routes: ['oral disintegrating tablet'],
    common_frequencies: ['PRN for acute (max 75 mg/day)', 'Every other day for prevention'],
    interactions_note: 'Dual acute/preventive CGRP antagonist. Avoid strong CYP3A4 inhibitors. Do not use with another gepant within 48 hours.',
  },
  {
    name: 'Botox',
    generic_name: 'onabotulinumtoxinA',
    category: 'Headache/Migraine',
    common_dosages: ['155 units (31 injection sites)', '195 units (39 injection sites with follow-the-pain)'],
    routes: ['intramuscular injection'],
    common_frequencies: ['Every 12 weeks'],
    monitoring: 'Assess headache frequency diary before each cycle. Monitor for neck weakness, dysphagia.',
    interactions_note: 'For chronic migraine (15+ headache days/month). Avoid with aminoglycosides. Effects may spread from injection site.',
  },

  // ---------------------------------------------------------------------------
  // Seizure / Epilepsy (~12)
  // ---------------------------------------------------------------------------
  {
    name: 'Keppra',
    generic_name: 'levetiracetam',
    category: 'Seizure/Epilepsy',
    common_dosages: ['250 mg', '500 mg', '750 mg', '1000 mg', '500 mg/5 mL solution'],
    routes: ['oral', 'intravenous'],
    common_frequencies: ['BID'],
    monitoring: 'CBC periodically. Monitor mood and behavioral changes (irritability, aggression).',
    interactions_note: 'Generally well-tolerated with few drug interactions. Behavioral side effects (Keppra rage) may require dose adjustment or switch.',
  },
  {
    name: 'Lamictal',
    generic_name: 'lamotrigine',
    category: 'Seizure/Epilepsy',
    common_dosages: ['25 mg', '50 mg', '100 mg', '150 mg', '200 mg', '250 mg', '25 mg chewable'],
    routes: ['oral'],
    common_frequencies: ['BID', 'Daily'],
    monitoring: 'Monitor for rash, especially during titration. Slow titration required (especially with valproate).',
    interactions_note: 'Valproate doubles lamotrigine levels (halve dose). Enzyme inducers (carbamazepine, phenytoin) reduce levels. Risk of SJS/TEN with rapid titration.',
  },
  {
    name: 'Tegretol',
    generic_name: 'carbamazepine',
    category: 'Seizure/Epilepsy',
    common_dosages: ['100 mg', '200 mg', '100 mg/5 mL suspension', '200 mg XR', '400 mg XR'],
    routes: ['oral'],
    common_frequencies: ['BID', 'TID', 'BID (XR)'],
    monitoring: 'CBC, LFTs, sodium level. Drug level (target 4-12 mcg/mL). HLA-B*1502 screening in Asian patients before starting.',
    interactions_note: 'Strong CYP3A4 inducer - reduces efficacy of many drugs including oral contraceptives. Risk of SJS (HLA-B*1502). Hyponatremia risk.',
  },
  {
    name: 'Trileptal',
    generic_name: 'oxcarbazepine',
    category: 'Seizure/Epilepsy',
    common_dosages: ['150 mg', '300 mg', '600 mg', '300 mg/5 mL suspension'],
    routes: ['oral'],
    common_frequencies: ['BID'],
    monitoring: 'Sodium level at baseline, 2-4 weeks, and periodically (hyponatremia risk higher than carbamazepine).',
    interactions_note: 'Mild enzyme inducer. Reduces efficacy of oral contraceptives. Cross-reactivity with carbamazepine allergy (~25%).',
  },
  {
    name: 'Dilantin',
    generic_name: 'phenytoin',
    category: 'Seizure/Epilepsy',
    common_dosages: ['100 mg', '200 mg ER', '300 mg ER', '125 mg/5 mL suspension'],
    routes: ['oral', 'intravenous'],
    common_frequencies: ['Daily (ER)', 'BID', 'TID'],
    monitoring: 'Free and total phenytoin levels (target total 10-20 mcg/mL, free 1-2 mcg/mL). CBC, LFTs, albumin. Monitor for gingival hyperplasia, nystagmus.',
    interactions_note: 'Highly protein-bound with nonlinear kinetics. Strong CYP inducer - many drug interactions. Reduces efficacy of oral contraceptives, warfarin metabolism altered.',
  },
  {
    name: 'Vimpat',
    generic_name: 'lacosamide',
    category: 'Seizure/Epilepsy',
    common_dosages: ['50 mg', '100 mg', '150 mg', '200 mg', '10 mg/mL solution', '200 mg/20 mL IV'],
    routes: ['oral', 'intravenous'],
    common_frequencies: ['BID'],
    monitoring: 'ECG at baseline (PR prolongation). Monitor for dizziness and cardiac conduction abnormalities.',
    interactions_note: 'Caution with other PR-prolonging drugs. Schedule V controlled substance. Generally fewer drug interactions than older AEDs.',
  },
  {
    name: 'Briviact',
    generic_name: 'brivaracetam',
    category: 'Seizure/Epilepsy',
    common_dosages: ['25 mg', '50 mg', '75 mg', '100 mg', '10 mg/mL solution'],
    routes: ['oral', 'intravenous'],
    common_frequencies: ['BID'],
    monitoring: 'Monitor for behavioral/psychiatric symptoms (less common than levetiracetam).',
    interactions_note: 'SV2A ligand similar to levetiracetam but higher affinity. May be better tolerated behaviorally. Schedule V.',
  },
  {
    name: 'Onfi',
    generic_name: 'clobazam',
    category: 'Seizure/Epilepsy',
    common_dosages: ['5 mg', '10 mg', '20 mg', '2.5 mg/mL suspension'],
    routes: ['oral'],
    common_frequencies: ['BID'],
    monitoring: 'CYP2C19 poor metabolizer status if poor response or excessive sedation. Monitor for sedation and tolerance.',
    interactions_note: 'Benzodiazepine - Schedule IV. Adjunctive for Lennox-Gastaut syndrome. Tolerance may develop. Taper when discontinuing.',
  },
  {
    name: 'Zonegran',
    generic_name: 'zonisamide',
    category: 'Seizure/Epilepsy',
    common_dosages: ['25 mg', '50 mg', '100 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily', 'BID'],
    monitoring: 'Serum bicarbonate (metabolic acidosis risk). Renal function. Monitor for kidney stones.',
    interactions_note: 'Sulfonamide derivative - contraindicated with sulfa allergy. Carbonic anhydrase inhibitor effects. Risk of kidney stones and oligohidrosis.',
  },
  {
    name: 'Fycompa',
    generic_name: 'perampanel',
    category: 'Seizure/Epilepsy',
    common_dosages: ['2 mg', '4 mg', '6 mg', '8 mg', '10 mg', '12 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS'],
    monitoring: 'Monitor for psychiatric/behavioral changes (aggression, hostility, irritability). Falls risk.',
    interactions_note: 'Schedule III controlled substance. AMPA receptor antagonist. Enzyme inducers reduce levels. Avoid alcohol. Give at bedtime.',
  },
  {
    name: 'Xcopri',
    generic_name: 'cenobamate',
    category: 'Seizure/Epilepsy',
    common_dosages: ['12.5 mg', '25 mg', '50 mg', '100 mg', '150 mg', '200 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily'],
    monitoring: 'Must use slow titration pack. Monitor for DRESS syndrome and QT shortening. LFTs periodically.',
    interactions_note: 'CYP2C19 inhibitor; CYP3A4 inducer. Reduces levels of oral contraceptives and other CYP3A4 substrates. REMS program due to DRESS risk.',
  },
  {
    name: 'Depakote',
    generic_name: 'valproic acid',
    category: 'Seizure/Epilepsy',
    common_dosages: ['250 mg', '500 mg', '125 mg sprinkle', '250 mg/5 mL syrup', '500 mg ER'],
    routes: ['oral', 'intravenous'],
    common_frequencies: ['BID', 'TID', 'Daily (ER)'],
    monitoring: 'LFTs at baseline and periodically. CBC with platelets. Drug level (target 50-100 mcg/mL). Ammonia if encephalopathy suspected.',
    interactions_note: 'Teratogenic - contraindicated in pregnancy. Doubles lamotrigine levels. Hepatotoxicity and pancreatitis risk. Weight gain common.',
  },

  // ---------------------------------------------------------------------------
  // Movement Disorders (~10)
  // ---------------------------------------------------------------------------
  {
    name: 'Sinemet',
    generic_name: 'carbidopa/levodopa',
    category: 'Movement Disorders',
    common_dosages: ['10/100 mg', '25/100 mg', '25/250 mg', '25/100 mg CR', '50/200 mg CR', '23.75/95 mg ER (Rytary)'],
    routes: ['oral'],
    common_frequencies: ['TID', 'QID', 'Every 4-6 hours'],
    monitoring: 'Monitor for dyskinesias, wearing-off, on-off fluctuations. Orthostatic blood pressure.',
    interactions_note: 'Avoid with non-selective MAOIs. Protein-rich meals may reduce absorption. Do not crush CR formulation.',
  },
  {
    name: 'Mirapex',
    generic_name: 'pramipexole',
    category: 'Movement Disorders',
    common_dosages: ['0.125 mg', '0.25 mg', '0.5 mg', '0.75 mg', '1 mg', '1.5 mg', '0.375 mg ER', '0.75 mg ER', '1.5 mg ER', '3 mg ER', '4.5 mg ER'],
    routes: ['oral'],
    common_frequencies: ['TID (IR)', 'Daily (ER)'],
    monitoring: 'Monitor for impulse control disorders (gambling, shopping, hypersexuality). Excessive daytime somnolence, orthostatic hypotension.',
    interactions_note: 'Dose adjustment required in renal impairment. Risk of sleep attacks - caution with driving.',
  },
  {
    name: 'Requip',
    generic_name: 'ropinirole',
    category: 'Movement Disorders',
    common_dosages: ['0.25 mg', '0.5 mg', '1 mg', '2 mg', '3 mg', '4 mg', '2 mg XL', '4 mg XL', '8 mg XL', '12 mg XL'],
    routes: ['oral'],
    common_frequencies: ['TID (IR)', 'Daily (XL)'],
    monitoring: 'Monitor for impulse control disorders, somnolence, orthostatic hypotension.',
    interactions_note: 'CYP1A2 substrate - levels affected by ciprofloxacin and smoking. Risk of augmentation when used for RLS.',
  },
  {
    name: 'Comtan',
    generic_name: 'entacapone',
    category: 'Movement Disorders',
    common_dosages: ['200 mg'],
    routes: ['oral'],
    common_frequencies: ['With each dose of carbidopa/levodopa (max 8 times/day)'],
    monitoring: 'LFTs periodically. Monitor for diarrhea, dyskinesias (may need to reduce levodopa dose), urine discoloration (brownish-orange).',
    interactions_note: 'COMT inhibitor - extends levodopa half-life. May intensify levodopa side effects. Available as Stalevo (combo with carbidopa/levodopa).',
  },
  {
    name: 'Symmetrel',
    generic_name: 'amantadine',
    category: 'Movement Disorders',
    common_dosages: ['100 mg', '100 mg capsule', '68 mg ER (Gocovri)', '137 mg ER (Gocovri)'],
    routes: ['oral'],
    common_frequencies: ['BID (IR)', 'QHS (ER/Gocovri)'],
    monitoring: 'Renal function (dose adjustment required). Monitor for hallucinations, livedo reticularis, peripheral edema.',
    interactions_note: 'Used for levodopa-induced dyskinesias and as early PD monotherapy. Anticholinergic properties. Avoid abrupt discontinuation.',
  },
  {
    name: 'Artane',
    generic_name: 'trihexyphenidyl',
    category: 'Movement Disorders',
    common_dosages: ['2 mg', '5 mg'],
    routes: ['oral'],
    common_frequencies: ['TID', 'BID'],
    monitoring: 'Monitor for anticholinergic side effects: dry mouth, constipation, urinary retention, blurred vision, confusion (especially in elderly).',
    interactions_note: 'Anticholinergic - avoid in elderly and patients with cognitive impairment. Used primarily for tremor-predominant PD in younger patients.',
  },
  {
    name: 'Xenazine',
    generic_name: 'tetrabenazine',
    category: 'Movement Disorders',
    common_dosages: ['12.5 mg', '25 mg'],
    routes: ['oral'],
    common_frequencies: ['BID', 'TID'],
    monitoring: 'CYP2D6 genotyping recommended (max 50 mg/day in poor metabolizers vs 100 mg/day). Monitor for depression, suicidality, parkinsonism, dysphagia.',
    interactions_note: 'VMAT2 inhibitor for Huntington chorea. Black box warning for depression/suicidality. Contraindicated with MAOIs and in suicidal/untreated depressed patients.',
  },
  {
    name: 'Austedo',
    generic_name: 'deutetrabenazine',
    category: 'Movement Disorders',
    common_dosages: ['6 mg', '9 mg', '12 mg'],
    routes: ['oral'],
    common_frequencies: ['BID'],
    monitoring: 'CYP2D6 genotyping recommended. Monitor for depression, suicidality, parkinsonism. Take with food.',
    interactions_note: 'Deuterated VMAT2 inhibitor - longer half-life and less peak-to-trough variation than tetrabenazine. Same black box warning for depression/suicidality.',
  },
  {
    name: 'Botox',
    generic_name: 'onabotulinumtoxinA',
    category: 'Movement Disorders',
    common_dosages: ['Variable by muscle group', '50-300 units per session (cervical dystonia)', '12.5-50 units per muscle (focal dystonia)'],
    routes: ['intramuscular injection'],
    common_frequencies: ['Every 12 weeks'],
    monitoring: 'Assess response and adjust dosing per muscle group. Monitor for dysphagia (cervical dystonia), weakness.',
    interactions_note: 'For cervical dystonia, blepharospasm, focal dystonias, spasticity. Avoid with aminoglycosides. Antibody formation may reduce efficacy over time.',
  },
  {
    name: 'Cogentin',
    generic_name: 'benztropine',
    category: 'Movement Disorders',
    common_dosages: ['0.5 mg', '1 mg', '2 mg'],
    routes: ['oral', 'intramuscular', 'intravenous'],
    common_frequencies: ['BID', 'TID'],
    monitoring: 'Monitor for anticholinergic effects: confusion, hallucinations (especially in elderly), urinary retention, constipation.',
    interactions_note: 'Anticholinergic used for drug-induced extrapyramidal symptoms and tremor-predominant PD. Avoid in elderly and with other anticholinergics.',
  },

  // ---------------------------------------------------------------------------
  // MS / Neuroimmunology (~10)
  // ---------------------------------------------------------------------------
  {
    name: 'Tecfidera',
    generic_name: 'dimethyl fumarate',
    category: 'MS/Neuroimmunology',
    common_dosages: ['120 mg', '240 mg'],
    routes: ['oral'],
    common_frequencies: ['BID (start 120 mg BID x 7 days, then 240 mg BID)'],
    monitoring: 'CBC with lymphocyte count every 6 months (risk of PML with lymphopenia). LFTs at baseline. Monitor for flushing and GI side effects.',
    interactions_note: 'GI side effects and flushing common at initiation - take with food. Hold if lymphocytes <500 for >6 months.',
  },
  {
    name: 'Gilenya',
    generic_name: 'fingolimod',
    category: 'MS/Neuroimmunology',
    common_dosages: ['0.5 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily'],
    monitoring: 'First-dose cardiac monitoring (6-hour observation for bradycardia). Ophthalmology exam at 3-4 months (macular edema). CBC, LFTs, VZV antibody before starting.',
    interactions_note: 'S1P receptor modulator. VZV vaccination 1 month before starting if seronegative. Rebound MS activity possible on discontinuation.',
  },
  {
    name: 'Tysabri',
    generic_name: 'natalizumab',
    category: 'MS/Neuroimmunology',
    common_dosages: ['300 mg IV infusion'],
    routes: ['intravenous'],
    common_frequencies: ['Every 4 weeks'],
    monitoring: 'JCV antibody index every 6 months (PML risk stratification). LFTs periodically. MRI brain surveillance.',
    interactions_note: 'TOUCH prescribing program required. PML risk increases with JCV+ status, prior immunosuppressant use, and treatment duration >2 years. High-efficacy therapy.',
  },
  {
    name: 'Ocrevus',
    generic_name: 'ocrelizumab',
    category: 'MS/Neuroimmunology',
    common_dosages: ['300 mg IV (initial doses 1 & 2, 2 weeks apart)', '600 mg IV (subsequent doses)'],
    routes: ['intravenous'],
    common_frequencies: ['Every 6 months (after initial split doses)'],
    monitoring: 'Hepatitis B screening before starting. Immunoglobulin levels periodically. Screen for infections before each infusion.',
    interactions_note: 'Anti-CD20 monoclonal antibody. Premedicate with methylprednisolone, antihistamine, and acetaminophen. Increased infection risk. Vaccinate before starting.',
  },
  {
    name: 'Copaxone',
    generic_name: 'glatiramer acetate',
    category: 'MS/Neuroimmunology',
    common_dosages: ['20 mg/mL prefilled syringe', '40 mg/mL prefilled syringe'],
    routes: ['subcutaneous'],
    common_frequencies: ['Daily (20 mg)', 'Three times weekly (40 mg)'],
    monitoring: 'Injection site reactions. Post-injection systemic reaction (flushing, chest tightness, palpitations - self-limited).',
    interactions_note: 'Generally well-tolerated. Rotate injection sites. Lipoatrophy may occur at injection sites.',
  },
  {
    name: 'Avonex',
    generic_name: 'interferon beta-1a',
    category: 'MS/Neuroimmunology',
    common_dosages: ['30 mcg/0.5 mL prefilled syringe'],
    routes: ['intramuscular'],
    common_frequencies: ['Weekly'],
    monitoring: 'CBC, LFTs at baseline, 1 month, 3 months, then every 6 months. Thyroid function annually. Monitor for depression and flu-like symptoms.',
    interactions_note: 'Flu-like symptoms common (pre-treat with NSAIDs/acetaminophen). Hepatotoxicity risk. May worsen depression. Neutralizing antibodies may reduce efficacy.',
  },
  {
    name: 'Mayzent',
    generic_name: 'siponimod',
    category: 'MS/Neuroimmunology',
    common_dosages: ['0.25 mg', '1 mg', '2 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily (titration pack for first 5 days, then 2 mg daily)'],
    monitoring: 'CYP2C9 genotyping required before starting (contraindicated in CYP2C9 *3/*3). First-dose cardiac monitoring. Ophthalmology exam. CBC, LFTs.',
    interactions_note: 'S1P receptor modulator for secondary progressive MS. CYP2C9 genotype determines dosing. VZV vaccination if seronegative.',
  },
  {
    name: 'Kesimpta',
    generic_name: 'ofatumumab',
    category: 'MS/Neuroimmunology',
    common_dosages: ['20 mg/0.4 mL prefilled pen'],
    routes: ['subcutaneous'],
    common_frequencies: ['Weekly x 3 (weeks 0, 1, 2), then monthly starting week 4'],
    monitoring: 'Hepatitis B screening before starting. Immunoglobulin levels. Monitor for infections.',
    interactions_note: 'Anti-CD20 monoclonal antibody (self-administered SC). Complete vaccinations before starting. Avoid live vaccines during and for 6 months after treatment.',
  },
  {
    name: 'Aubagio',
    generic_name: 'teriflunomide',
    category: 'MS/Neuroimmunology',
    common_dosages: ['7 mg', '14 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily'],
    monitoring: 'LFTs monthly for 6 months then periodically. CBC. Blood pressure. Tuberculosis screening before starting.',
    interactions_note: 'Teratogenic - pregnancy test required. Accelerated elimination with cholestyramine or activated charcoal if needed. Long half-life (~18-19 days). Alopecia common.',
  },
  {
    name: 'Mavenclad',
    generic_name: 'cladribine',
    category: 'MS/Neuroimmunology',
    common_dosages: ['10 mg tablet'],
    routes: ['oral'],
    common_frequencies: ['2 treatment courses: Year 1 and Year 2 (each course = 2 cycles, 4-5 days each, 1 month apart)'],
    monitoring: 'CBC with lymphocyte count at baseline, 2 and 6 months after each course. Screen for infections, malignancy, and Hepatitis B/C/TB before starting.',
    interactions_note: 'Immune reconstitution therapy - no continuous dosing needed after 2 years. Cumulative dose based on weight (3.5 mg/kg total). Lymphopenia expected.',
  },

  // ---------------------------------------------------------------------------
  // Neuromuscular (~5)
  // ---------------------------------------------------------------------------
  {
    name: 'Mestinon',
    generic_name: 'pyridostigmine',
    category: 'Neuromuscular',
    common_dosages: ['60 mg', '180 mg SR', '60 mg/5 mL syrup'],
    routes: ['oral'],
    common_frequencies: ['TID', 'QID', 'Every 4-6 hours'],
    monitoring: 'Monitor for cholinergic side effects (diarrhea, cramping, salivation, bradycardia). Watch for cholinergic crisis vs myasthenic crisis.',
    interactions_note: 'Acetylcholinesterase inhibitor for myasthenia gravis. Take 30-60 min before meals. Avoid with beta-blockers (bradycardia risk).',
  },
  {
    name: 'Prednisone',
    generic_name: 'prednisone',
    category: 'Neuromuscular',
    common_dosages: ['5 mg', '10 mg', '20 mg', '50 mg', '1 mg/kg/day (induction)'],
    routes: ['oral'],
    common_frequencies: ['Daily', 'Every other day (maintenance/taper)'],
    monitoring: 'Blood glucose, bone density (DEXA), blood pressure, weight, intraocular pressure, mood changes. Consider PPI, calcium/vitamin D, PJP prophylaxis.',
    interactions_note: 'Long-term use: Cushing syndrome, osteoporosis, diabetes, cataracts, adrenal suppression. Taper slowly after prolonged use. Used in MG, inflammatory myopathies, CIDP.',
  },
  {
    name: 'Imuran',
    generic_name: 'azathioprine',
    category: 'Neuromuscular',
    common_dosages: ['50 mg', '75 mg', '100 mg', '150 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily', 'BID'],
    monitoring: 'TPMT genotyping before starting. CBC weekly x 4, then every 2 weeks x 8, then monthly. LFTs periodically.',
    interactions_note: 'Steroid-sparing immunosuppressant for MG. Contraindicated with allopurinol (severe myelosuppression). Onset of action 3-6 months. TPMT deficiency increases toxicity risk.',
  },
  {
    name: 'CellCept',
    generic_name: 'mycophenolate mofetil',
    category: 'Neuromuscular',
    common_dosages: ['250 mg', '500 mg', '200 mg/mL suspension'],
    routes: ['oral'],
    common_frequencies: ['BID (typically 1000-1500 mg BID)'],
    monitoring: 'CBC weekly x 4, then every 2 weeks x 2 months, then monthly. Pregnancy test before starting (teratogenic).',
    interactions_note: 'Steroid-sparing immunosuppressant for MG and inflammatory neuropathies. Onset 2-6 months. Teratogenic - requires REMS. GI side effects common.',
  },
  {
    name: 'IVIG',
    generic_name: 'immune globulin intravenous',
    category: 'Neuromuscular',
    common_dosages: ['0.4 g/kg/day x 5 days (induction)', '1 g/kg/day x 2 days (induction)', '0.4-1 g/kg every 3-4 weeks (maintenance)'],
    routes: ['intravenous', 'subcutaneous (SCIg maintenance)'],
    common_frequencies: ['Every 3-4 weeks (maintenance)', '5-day induction for acute exacerbation'],
    monitoring: 'Renal function (avoid sucrose-containing products in renal impairment). IgA level (anaphylaxis risk if IgA-deficient). Monitor for headache, aseptic meningitis, thrombosis.',
    interactions_note: 'Used in MG exacerbation, CIDP, GBS, inflammatory myopathies. Premedicate with acetaminophen/diphenhydramine. Avoid live vaccines for 3 months after infusion.',
  },

  // ---------------------------------------------------------------------------
  // Cerebrovascular (~6)
  // ---------------------------------------------------------------------------
  {
    name: 'Aspirin',
    generic_name: 'aspirin',
    category: 'Cerebrovascular',
    common_dosages: ['81 mg', '325 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily'],
    monitoring: 'Monitor for GI bleeding. CBC periodically. Consider PPI for GI protection.',
    interactions_note: 'Antiplatelet for secondary stroke prevention. Avoid with anticoagulants unless specifically indicated (increased bleeding risk). NSAIDs may reduce antiplatelet effect.',
  },
  {
    name: 'Plavix',
    generic_name: 'clopidogrel',
    category: 'Cerebrovascular',
    common_dosages: ['75 mg', '300 mg (loading dose)'],
    routes: ['oral'],
    common_frequencies: ['Daily'],
    monitoring: 'CBC periodically. Monitor for bleeding, TTP (rare).',
    interactions_note: 'CYP2C19 prodrug - poor metabolizers may not benefit (consider genotyping). PPIs (especially omeprazole) may reduce efficacy. Used in dual antiplatelet therapy (DAPT) with aspirin for 21-90 days post-minor stroke/TIA.',
  },
  {
    name: 'Brilinta',
    generic_name: 'ticagrelor',
    category: 'Cerebrovascular',
    common_dosages: ['90 mg', '60 mg'],
    routes: ['oral'],
    common_frequencies: ['BID (with aspirin 81 mg daily)'],
    monitoring: 'Monitor for dyspnea (common, usually self-limited), bleeding, bradyarrhythmias.',
    interactions_note: 'Direct-acting antiplatelet (no CYP2C19 dependency). Aspirin dose must be 81 mg or less (higher doses reduce ticagrelor efficacy). Avoid with strong CYP3A4 inhibitors/inducers.',
  },
  {
    name: 'Coumadin',
    generic_name: 'warfarin',
    category: 'Cerebrovascular',
    common_dosages: ['1 mg', '2 mg', '2.5 mg', '3 mg', '4 mg', '5 mg', '6 mg', '7.5 mg', '10 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily'],
    monitoring: 'INR regularly (target 2.0-3.0 for stroke prevention in AFib, 2.5-3.5 for mechanical valves). Frequent monitoring with diet/medication changes.',
    interactions_note: 'Numerous food (vitamin K) and drug interactions. CYP2C9/VKORC1 genotyping may guide dosing. Bridging with heparin for procedures. Vitamin K for reversal.',
  },
  {
    name: 'Eliquis',
    generic_name: 'apixaban',
    category: 'Cerebrovascular',
    common_dosages: ['2.5 mg', '5 mg'],
    routes: ['oral'],
    common_frequencies: ['BID'],
    monitoring: 'Renal function annually or more frequently if impaired. No routine coagulation monitoring required.',
    interactions_note: 'Direct factor Xa inhibitor for stroke prevention in AFib. Dose reduce to 2.5 mg BID if 2 of 3: age >=80, weight <=60 kg, Cr >=1.5. Avoid with strong dual CYP3A4 + P-gp inhibitors.',
  },
  {
    name: 'Xarelto',
    generic_name: 'rivaroxaban',
    category: 'Cerebrovascular',
    common_dosages: ['10 mg', '15 mg', '20 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily (take 15 mg and 20 mg with food)'],
    monitoring: 'Renal function (avoid if CrCl <15 mL/min). No routine coagulation monitoring.',
    interactions_note: 'Direct factor Xa inhibitor. Must take with food for adequate absorption (15 mg and 20 mg doses). Avoid with strong CYP3A4 + P-gp inhibitors. Andexanet alfa for reversal.',
  },

  // ---------------------------------------------------------------------------
  // Sleep (~5)
  // ---------------------------------------------------------------------------
  {
    name: 'Melatonin',
    generic_name: 'melatonin',
    category: 'Sleep',
    common_dosages: ['0.5 mg', '1 mg', '3 mg', '5 mg', '10 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS (30-60 min before bedtime)'],
    monitoring: 'Assess sleep quality and daytime functioning.',
    interactions_note: 'OTC supplement. Lower doses (0.5-1 mg) often more physiologic and effective than higher doses. May interact with warfarin, immunosuppressants, diabetes medications.',
  },
  {
    name: 'Desyrel',
    generic_name: 'trazodone',
    category: 'Sleep',
    common_dosages: ['25 mg', '50 mg', '100 mg', '150 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS'],
    monitoring: 'Monitor for orthostatic hypotension, priapism (rare but serious), excessive sedation.',
    interactions_note: 'Serotonin modulator used off-label for insomnia at low doses. Serotonin syndrome risk with other serotonergic drugs. Take shortly before bedtime.',
  },
  {
    name: 'Belsomra',
    generic_name: 'suvorexant',
    category: 'Sleep',
    common_dosages: ['5 mg', '10 mg', '15 mg', '20 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS (within 30 min of bedtime)'],
    monitoring: 'Monitor for next-day somnolence, sleep paralysis, hypnagogic/hypnopompic hallucinations.',
    interactions_note: 'Dual orexin receptor antagonist. Schedule IV. Reduce dose with moderate CYP3A4 inhibitors. Avoid with strong CYP3A4 inhibitors. Allow 7+ hours before planned waking.',
  },
  {
    name: 'Provigil',
    generic_name: 'modafinil',
    category: 'Sleep',
    common_dosages: ['100 mg', '200 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily (morning)', 'Split dose (morning and noon) for narcolepsy'],
    monitoring: 'Blood pressure, heart rate. Monitor for rash (SJS reported rarely). Psychiatric symptoms.',
    interactions_note: 'Schedule IV. Wakefulness-promoting agent for narcolepsy, OSA, shift work disorder. CYP3A4 inducer - reduces efficacy of oral contraceptives.',
  },
  {
    name: 'Xyrem',
    generic_name: 'sodium oxybate',
    category: 'Sleep',
    common_dosages: ['2.25 g/dose', '3 g/dose', '3.75 g/dose', '4.5 g/dose'],
    routes: ['oral solution'],
    common_frequencies: ['BID at night (first dose at bedtime, second dose 2.5-4 hours later)'],
    monitoring: 'Respiratory depression risk - avoid with other CNS depressants and alcohol. Monitor for depression, sleepwalking, enuresis.',
    interactions_note: 'REMS program required (through certified pharmacy only). Schedule III. For narcolepsy with cataplexy. High sodium content - monitor in salt-restricted patients.',
  },

  // ---------------------------------------------------------------------------
  // Pain / Neuropathy (~8)
  // ---------------------------------------------------------------------------
  {
    name: 'Neurontin',
    generic_name: 'gabapentin',
    category: 'Pain/Neuropathy',
    common_dosages: ['100 mg', '300 mg', '400 mg', '600 mg', '800 mg'],
    routes: ['oral'],
    common_frequencies: ['TID', 'BID (may start lower and titrate)'],
    monitoring: 'Renal function (dose adjustment required). Monitor for sedation, dizziness, peripheral edema, weight gain.',
    interactions_note: 'First-line for neuropathic pain. Dose adjust in renal impairment. May cause respiratory depression with opioids. Taper when discontinuing.',
  },
  {
    name: 'Lyrica',
    generic_name: 'pregabalin',
    category: 'Pain/Neuropathy',
    common_dosages: ['25 mg', '50 mg', '75 mg', '100 mg', '150 mg', '200 mg', '300 mg'],
    routes: ['oral'],
    common_frequencies: ['BID', 'TID'],
    monitoring: 'Renal function (dose adjustment in impairment). Monitor for weight gain, peripheral edema, dizziness, blurred vision.',
    interactions_note: 'Schedule V controlled substance. Linear pharmacokinetics (more predictable than gabapentin). Taper over 1 week when discontinuing.',
  },
  {
    name: 'Cymbalta',
    generic_name: 'duloxetine',
    category: 'Pain/Neuropathy',
    common_dosages: ['20 mg', '30 mg', '60 mg'],
    routes: ['oral'],
    common_frequencies: ['Daily', 'BID (60 mg BID for some pain conditions)'],
    monitoring: 'LFTs (avoid in hepatic impairment). Blood pressure. Monitor for serotonin syndrome, suicidality in young adults.',
    interactions_note: 'SNRI approved for diabetic peripheral neuropathy and fibromyalgia. Avoid with MAOIs and thioridazine. Hepatotoxicity risk - avoid in liver disease. Discontinuation syndrome with abrupt stop.',
  },
  {
    name: 'Elavil',
    generic_name: 'amitriptyline',
    category: 'Pain/Neuropathy',
    common_dosages: ['10 mg', '25 mg', '50 mg', '75 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS'],
    monitoring: 'ECG at baseline in patients >40 or with cardiac history. Monitor for anticholinergic effects, weight gain, sedation.',
    interactions_note: 'TCA used off-label for neuropathic pain at lower doses than for depression. Avoid with MAOIs. QTc prolongation risk. Start low and titrate.',
  },
  {
    name: 'Pamelor',
    generic_name: 'nortriptyline',
    category: 'Pain/Neuropathy',
    common_dosages: ['10 mg', '25 mg', '50 mg', '75 mg'],
    routes: ['oral'],
    common_frequencies: ['QHS', 'BID'],
    monitoring: 'Drug level if needed (target 50-150 ng/mL for depression). ECG at baseline. Monitor anticholinergic effects.',
    interactions_note: 'TCA with fewer anticholinergic effects than amitriptyline. Used for neuropathic pain. Avoid with MAOIs. QTc prolongation risk.',
  },
  {
    name: 'Capsaicin cream',
    generic_name: 'capsaicin',
    category: 'Pain/Neuropathy',
    common_dosages: ['0.025% cream', '0.075% cream', '8% patch (Qutenza)'],
    routes: ['topical'],
    common_frequencies: ['TID-QID (OTC cream)', 'Every 3 months (8% patch - clinic application)'],
    monitoring: 'Application site reactions. 8% patch requires clinic administration with pre-treatment topical anesthetic.',
    interactions_note: 'Depletes substance P. Burning sensation common initially (improves with continued use). 8% patch (Qutenza) is prescription-only and applied by healthcare provider.',
  },
  {
    name: 'Tegretol',
    generic_name: 'carbamazepine',
    category: 'Pain/Neuropathy',
    common_dosages: ['100 mg', '200 mg', '200 mg XR', '400 mg XR'],
    routes: ['oral'],
    common_frequencies: ['BID', 'TID'],
    monitoring: 'Drug level (target 4-12 mcg/mL). CBC, LFTs, sodium. HLA-B*1502 screening in Asian patients.',
    interactions_note: 'First-line for trigeminal neuralgia. Strong CYP3A4 inducer. Auto-induction of own metabolism. Risk of SJS, aplastic anemia, agranulocytosis.',
  },
  {
    name: 'Lioresal',
    generic_name: 'baclofen',
    category: 'Pain/Neuropathy',
    common_dosages: ['5 mg', '10 mg', '20 mg'],
    routes: ['oral', 'intrathecal'],
    common_frequencies: ['TID (start 5 mg TID, titrate up)'],
    monitoring: 'Renal function (dose adjustment). Monitor for sedation, weakness, withdrawal symptoms if abruptly discontinued.',
    interactions_note: 'GABA-B agonist for spasticity and neuropathic pain. Never discontinue abruptly (risk of seizures, hallucinations, death). Intrathecal pump for severe spasticity. Excreted renally.',
  },
]

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Search the formulary with case-insensitive fuzzy matching on name and generic_name.
 * Returns items where the query appears as a substring in either field.
 */
export function searchFormulary(query: string): FormularyItem[] {
  if (!query || query.trim().length === 0) return []
  const lowerQuery = query.toLowerCase().trim()

  return NEURO_FORMULARY.filter((item) => {
    const nameMatch = item.name.toLowerCase().includes(lowerQuery)
    const genericMatch = item.generic_name.toLowerCase().includes(lowerQuery)
    return nameMatch || genericMatch
  })
}

/**
 * Get all formulary items for a given category (case-insensitive match).
 */
export function getFormularyByCategory(category: string): FormularyItem[] {
  const lowerCategory = category.toLowerCase().trim()
  return NEURO_FORMULARY.filter(
    (item) => item.category.toLowerCase() === lowerCategory
  )
}
