'use client'

import { useState, useEffect, useCallback } from 'react'
import type {
  PostCallSummary as PostCallSummaryType,
  EscalationTier,
} from '@/lib/follow-up/types'

interface PostCallSummaryProps {
  sessionId: string
}

const TIER_COLORS: Record<EscalationTier, string> = {
  urgent: '#DC2626',
  same_day: '#EA580C',
  next_visit: '#EAB308',
  informational: '#16A34A',
}

const TIER_LABELS: Record<EscalationTier, string> = {
  urgent: 'URGENT',
  same_day: 'SAME-DAY',
  next_visit: 'NEXT VISIT',
  informational: 'INFO',
}

function SectionHeader({ children }: { children: React.ReactNode }) {
  return (
    <div style={{
      color: '#64748b',
      fontSize: '11px',
      fontWeight: 600,
      textTransform: 'uppercase',
      letterSpacing: '0.5px',
      marginBottom: '8px',
      marginTop: '20px',
    }}>
      {children}
    </div>
  )
}

function formatSummaryAsText(summary: PostCallSummaryType): string {
  const lines: string[] = []

  lines.push('POST-VISIT FOLLOW-UP SUMMARY')
  lines.push('='.repeat(40))
  lines.push(`Date: ${summary.date}`)
  lines.push(`Patient: ${summary.patientName}`)
  lines.push(`Visit Date: ${summary.visitDate}`)
  lines.push(`Provider: ${summary.providerName}`)
  lines.push(`Method: ${summary.followUpMethod.toUpperCase()}`)
  lines.push(`Duration: ${summary.durationMinutes} minutes`)
  lines.push(`Informant: ${summary.informant}`)
  lines.push('')

  lines.push('MEDICATION STATUS')
  lines.push('-'.repeat(30))
  summary.medicationStatus.forEach((med) => {
    const filled = med.filled === true ? 'Yes' : med.filled === false ? 'No' : 'Unknown'
    const taking = med.taking === true ? 'Yes' : med.taking === false ? 'No' : 'Unknown'
    lines.push(`  ${med.medication}: Filled=${filled}, Taking=${taking}`)
    if (med.sideEffects.length > 0) {
      lines.push(`    Side Effects: ${med.sideEffects.join(', ')}`)
    }
  })
  lines.push('')

  lines.push('SYMPTOM UPDATE')
  lines.push('-'.repeat(30))
  if (summary.symptomUpdate.newSymptoms.length > 0) {
    lines.push(`  New Symptoms: ${summary.symptomUpdate.newSymptoms.join(', ')}`)
  }
  if (summary.symptomUpdate.existingSymptoms) {
    lines.push(`  Existing Symptoms: ${summary.symptomUpdate.existingSymptoms}`)
  }
  lines.push('')

  lines.push('FUNCTIONAL STATUS')
  lines.push('-'.repeat(30))
  lines.push(`  Status: ${summary.functionalStatus}`)
  if (summary.functionalDetails) {
    lines.push(`  Details: ${summary.functionalDetails}`)
  }
  lines.push('')

  if (summary.patientQuestions.length > 0) {
    lines.push('PATIENT QUESTIONS')
    lines.push('-'.repeat(30))
    summary.patientQuestions.forEach((q, i) => {
      lines.push(`  ${i + 1}. ${q}`)
    })
    lines.push('')
  }

  if (summary.escalationFlags.length > 0) {
    lines.push('ESCALATION FLAGS')
    lines.push('-'.repeat(30))
    summary.escalationFlags.forEach((flag) => {
      lines.push(`  [${flag.tier.toUpperCase()}] ${flag.category}: ${flag.triggerText}`)
      lines.push(`    Action: ${flag.recommendedAction}`)
    })
    lines.push('')
  }

  lines.push('AI RECOMMENDATION')
  lines.push('-'.repeat(30))
  lines.push(`  ${summary.aiRecommendation}`)
  lines.push('')
  lines.push('Generated by AI Follow-Up Agent | Reviewed by: [pending clinician review]')

  return lines.join('\n')
}

export default function PostCallSummary({ sessionId }: PostCallSummaryProps) {
  const [summary, setSummary] = useState<PostCallSummaryType | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    let cancelled = false

    async function fetchSummary() {
      setLoading(true)
      setError(null)
      try {
        const res = await fetch(`/api/follow-up/${sessionId}/summary`)
        if (!res.ok) {
          throw new Error(`Failed to fetch summary (${res.status})`)
        }
        const data = await res.json()
        if (!cancelled) {
          setSummary(data)
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load summary')
        }
      } finally {
        if (!cancelled) {
          setLoading(false)
        }
      }
    }

    fetchSummary()
    return () => { cancelled = true }
  }, [sessionId])

  const handleCopy = useCallback(async () => {
    if (!summary) return
    try {
      await navigator.clipboard.writeText(formatSummaryAsText(summary))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for environments without clipboard API
      const textArea = document.createElement('textarea')
      textArea.value = formatSummaryAsText(summary)
      document.body.appendChild(textArea)
      textArea.select()
      document.execCommand('copy')
      document.body.removeChild(textArea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }, [summary])

  if (loading) {
    return (
      <div style={{
        background: '#1e293b',
        border: '1px solid #334155',
        borderRadius: '12px',
        padding: '40px 24px',
        textAlign: 'center',
      }}>
        <div style={{
          color: '#94a3b8',
          fontSize: '14px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '10px',
        }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ animation: 'spin 1s linear infinite' }}>
            <line x1="12" y1="2" x2="12" y2="6" />
            <line x1="12" y1="18" x2="12" y2="22" />
            <line x1="4.93" y1="4.93" x2="7.76" y2="7.76" />
            <line x1="16.24" y1="16.24" x2="19.07" y2="19.07" />
            <line x1="2" y1="12" x2="6" y2="12" />
            <line x1="18" y1="12" x2="22" y2="12" />
            <line x1="4.93" y1="19.07" x2="7.76" y2="16.24" />
            <line x1="16.24" y1="7.76" x2="19.07" y2="4.93" />
          </svg>
          Generating summary...
        </div>
        <style>{`
          @keyframes spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
          }
        `}</style>
      </div>
    )
  }

  if (error) {
    return (
      <div style={{
        background: '#1e293b',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        borderRadius: '12px',
        padding: '24px',
        textAlign: 'center',
      }}>
        <div style={{ color: '#EF4444', fontSize: '14px' }}>{error}</div>
      </div>
    )
  }

  if (!summary) return null

  const functionalColor = summary.functionalStatus === 'better'
    ? '#22C55E'
    : summary.functionalStatus === 'worse'
      ? '#EF4444'
      : '#EAB308'

  return (
    <div style={{
      background: '#1e293b',
      border: '1px solid #334155',
      borderRadius: '12px',
      padding: '24px',
    }}>
      {/* Title */}
      <div style={{
        color: 'white',
        fontSize: '16px',
        fontWeight: 700,
        letterSpacing: '0.5px',
        textAlign: 'center',
        marginBottom: '4px',
      }}>
        POST-VISIT FOLLOW-UP SUMMARY
      </div>

      {/* Header meta */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '8px 16px',
        background: '#334155',
        borderRadius: '8px',
        padding: '12px 16px',
        marginTop: '16px',
      }}>
        <div>
          <span style={{ color: '#64748b', fontSize: '11px' }}>Date: </span>
          <span style={{ color: '#e2e8f0', fontSize: '13px' }}>{summary.date}</span>
        </div>
        <div>
          <span style={{ color: '#64748b', fontSize: '11px' }}>Patient: </span>
          <span style={{ color: '#e2e8f0', fontSize: '13px' }}>{summary.patientName}</span>
        </div>
        <div>
          <span style={{ color: '#64748b', fontSize: '11px' }}>Visit Date: </span>
          <span style={{ color: '#e2e8f0', fontSize: '13px' }}>{summary.visitDate}</span>
        </div>
        <div>
          <span style={{ color: '#64748b', fontSize: '11px' }}>Provider: </span>
          <span style={{ color: '#e2e8f0', fontSize: '13px' }}>{summary.providerName}</span>
        </div>
        <div>
          <span style={{ color: '#64748b', fontSize: '11px' }}>Method: </span>
          <span style={{ color: '#e2e8f0', fontSize: '13px' }}>{summary.followUpMethod.toUpperCase()}</span>
        </div>
        <div>
          <span style={{ color: '#64748b', fontSize: '11px' }}>Duration: </span>
          <span style={{ color: '#e2e8f0', fontSize: '13px' }}>{summary.durationMinutes} min</span>
        </div>
      </div>

      {/* Medication Status */}
      <SectionHeader>Medication Status</SectionHeader>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        {summary.medicationStatus.map((med, i) => (
          <div key={i} style={{
            background: '#334155',
            borderRadius: '8px',
            padding: '10px 12px',
          }}>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: med.sideEffects.length > 0 ? '6px' : 0,
            }}>
              <span style={{ color: 'white', fontSize: '13px', fontWeight: 500 }}>
                {med.medication}
              </span>
              <div style={{ display: 'flex', gap: '12px' }}>
                <span style={{ fontSize: '12px' }}>
                  <span style={{ color: '#64748b' }}>Filled: </span>
                  <span style={{ color: med.filled === true ? '#22C55E' : med.filled === false ? '#EF4444' : '#64748b' }}>
                    {med.filled === true ? 'Yes' : med.filled === false ? 'No' : '--'}
                  </span>
                </span>
                <span style={{ fontSize: '12px' }}>
                  <span style={{ color: '#64748b' }}>Taking: </span>
                  <span style={{ color: med.taking === true ? '#22C55E' : med.taking === false ? '#EF4444' : '#64748b' }}>
                    {med.taking === true ? 'Yes' : med.taking === false ? 'No' : '--'}
                  </span>
                </span>
              </div>
            </div>
            {med.sideEffects.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px' }}>
                {med.sideEffects.map((se, j) => (
                  <span key={j} style={{
                    fontSize: '11px',
                    color: '#F87171',
                    background: 'rgba(239, 68, 68, 0.12)',
                    padding: '2px 8px',
                    borderRadius: '4px',
                  }}>
                    {se}
                  </span>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Symptom Update */}
      <SectionHeader>Symptom Update</SectionHeader>
      <div style={{
        background: '#334155',
        borderRadius: '8px',
        padding: '12px',
      }}>
        {summary.symptomUpdate.newSymptoms.length > 0 && (
          <div style={{ marginBottom: '8px' }}>
            <span style={{ color: '#64748b', fontSize: '11px', fontWeight: 600 }}>New Symptoms: </span>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', marginTop: '4px' }}>
              {summary.symptomUpdate.newSymptoms.map((s, i) => (
                <span key={i} style={{
                  fontSize: '12px',
                  color: '#FBBF24',
                  background: 'rgba(234, 179, 8, 0.12)',
                  padding: '2px 8px',
                  borderRadius: '4px',
                }}>
                  {s}
                </span>
              ))}
            </div>
          </div>
        )}
        {summary.symptomUpdate.existingSymptoms && (
          <div>
            <span style={{ color: '#64748b', fontSize: '11px', fontWeight: 600 }}>Existing: </span>
            <span style={{ color: '#94a3b8', fontSize: '13px' }}>
              {summary.symptomUpdate.existingSymptoms}
            </span>
          </div>
        )}
        {summary.symptomUpdate.newSymptoms.length === 0 && !summary.symptomUpdate.existingSymptoms && (
          <span style={{ color: '#64748b', fontSize: '13px' }}>No symptoms reported</span>
        )}
      </div>

      {/* Functional Status */}
      <SectionHeader>Functional Status</SectionHeader>
      <div style={{
        background: '#334155',
        borderRadius: '8px',
        padding: '12px',
      }}>
        <span style={{
          display: 'inline-block',
          padding: '3px 10px',
          borderRadius: '6px',
          background: `${functionalColor}1A`,
          color: functionalColor,
          fontSize: '13px',
          fontWeight: 600,
        }}>
          {summary.functionalStatus.charAt(0).toUpperCase() + summary.functionalStatus.slice(1)}
        </span>
        {summary.functionalDetails && (
          <div style={{ color: '#94a3b8', fontSize: '13px', marginTop: '8px', lineHeight: '1.5' }}>
            {summary.functionalDetails}
          </div>
        )}
      </div>

      {/* Patient Questions */}
      <SectionHeader>Patient Questions</SectionHeader>
      {summary.patientQuestions.length === 0 ? (
        <div style={{ color: '#64748b', fontSize: '13px' }}>None</div>
      ) : (
        <div style={{
          background: '#334155',
          borderRadius: '8px',
          padding: '12px',
          display: 'flex',
          flexDirection: 'column',
          gap: '6px',
        }}>
          {summary.patientQuestions.map((q, i) => (
            <div key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start' }}>
              <span style={{ color: '#64748b', fontSize: '12px', fontWeight: 600, minWidth: '20px' }}>
                {i + 1}.
              </span>
              <span style={{ color: '#e2e8f0', fontSize: '13px', lineHeight: '1.5' }}>{q}</span>
            </div>
          ))}
        </div>
      )}

      {/* Escalation Flags */}
      <SectionHeader>Escalation Flags</SectionHeader>
      {summary.escalationFlags.length === 0 ? (
        <div style={{ color: '#64748b', fontSize: '13px' }}>None</div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {summary.escalationFlags.map((flag, i) => {
            const tierColor = TIER_COLORS[flag.tier]
            return (
              <div key={i} style={{
                background: '#334155',
                borderRadius: '8px',
                padding: '10px 12px',
                borderLeft: `3px solid ${tierColor}`,
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                  <span style={{
                    fontSize: '10px',
                    fontWeight: 700,
                    color: 'white',
                    background: tierColor,
                    padding: '2px 8px',
                    borderRadius: '4px',
                  }}>
                    {TIER_LABELS[flag.tier]}
                  </span>
                  <span style={{ color: '#94a3b8', fontSize: '12px' }}>{flag.category}</span>
                </div>
                <div style={{ color: '#e2e8f0', fontSize: '13px', marginBottom: '4px', lineHeight: '1.5' }}>
                  &ldquo;{flag.triggerText}&rdquo;
                </div>
                <div style={{ color: '#94a3b8', fontSize: '12px' }}>
                  <strong style={{ color: '#94a3b8' }}>Action:</strong> {flag.recommendedAction}
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* AI Recommendation */}
      <SectionHeader>AI Recommendation</SectionHeader>
      <div style={{
        background: 'rgba(59, 130, 246, 0.08)',
        border: '1px solid rgba(59, 130, 246, 0.2)',
        borderRadius: '8px',
        padding: '12px 16px',
        display: 'flex',
        gap: '10px',
        alignItems: 'flex-start',
      }}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#60A5FA" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0, marginTop: '2px' }}>
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="16" x2="12" y2="12" />
          <line x1="12" y1="8" x2="12.01" y2="8" />
        </svg>
        <div style={{ color: '#93C5FD', fontSize: '13px', lineHeight: '1.6' }}>
          {summary.aiRecommendation}
        </div>
      </div>

      {/* Footer */}
      <div style={{
        marginTop: '24px',
        paddingTop: '16px',
        borderTop: '1px solid #334155',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      }}>
        <div style={{
          color: '#64748b',
          fontSize: '11px',
          fontStyle: 'italic',
          lineHeight: '1.5',
        }}>
          Generated by AI Follow-Up Agent | Reviewed by: [pending clinician review]
        </div>
        <button
          onClick={handleCopy}
          style={{
            padding: '8px 16px',
            borderRadius: '8px',
            background: '#334155',
            color: copied ? '#22C55E' : 'white',
            border: '1px solid #475569',
            fontSize: '12px',
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.15s ease',
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            flexShrink: 0,
          }}
        >
          {copied ? (
            <>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#22C55E" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12" />
              </svg>
              Copied
            </>
          ) : (
            <>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
              </svg>
              Copy to Clipboard
            </>
          )}
        </button>
      </div>
    </div>
  )
}
