'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import type { HistorianTranscriptEntry, HistorianStructuredOutput, HistorianRedFlag, HistorianSessionType } from '@/lib/historianTypes'
import type { LocalizerResponse } from '@/lib/consult/localizer-types'
import type { SaveScaleResponsesArgs } from '@/lib/consult/scales'
import { detectRedFlags } from '@/lib/consult/red-flags/red-flag-detector'
import type { DetectedFlag } from '@/lib/consult/red-flags/red-flag-types'

type SessionStatus = 'idle' | 'connecting' | 'active' | 'ending' | 'complete' | 'error' | 'safety_escalation'

interface UseRealtimeSessionOptions {
  sessionType: HistorianSessionType
  referralReason?: string
  patientName?: string
  patientContext?: string
  /**
   * Optional stable ID passed to the localizer for logging/tracing.
   * Typically a UUID generated by the parent before the session starts.
   */
  consultId?: string
  /**
   * Enable the mid-session localizer (default: true).
   * Set to false to disable entirely for testing or lightweight sessions.
   */
  enableLocalizer?: boolean
  /** Called when a new localizer result arrives. */
  onLocalizerUpdate?: (data: LocalizerResponse) => void
  /** Called when red flags are detected in patient speech. */
  onRedFlagDetected?: (flags: DetectedFlag[]) => void
  onSafetyEscalation?: () => void
  onComplete?: (data: {
    structuredOutput: HistorianStructuredOutput | null
    narrativeSummary: string | null
    redFlags: HistorianRedFlag[]
    safetyEscalated: boolean
    transcript: HistorianTranscriptEntry[]
    duration: number
    questionCount: number
  }) => void
  /** Called when the historian AI completes a scale administration via save_scale_responses tool */
  onScaleComplete?: (args: SaveScaleResponsesArgs) => void
}

interface UseRealtimeSessionResult {
  status: SessionStatus
  transcript: HistorianTranscriptEntry[]
  currentAssistantText: string
  currentUserText: string
  isAiSpeaking: boolean
  isUserSpeaking: boolean
  duration: number
  error: string | null
  /** Latest localizer result — null until the first run completes. */
  localizerData: LocalizerResponse | null
  /** True while a localizer run is in flight. */
  localizerLoading: boolean
  startSession: () => Promise<void>
  endSession: () => void
  /**
   * Injects scale administration instructions into the live session by sending
   * a session.update event on the data channel, then triggering a new response.
   * No-op if the session is not active or the data channel is closed.
   */
  injectScaleAdministration: (instructionBlock: string) => void
  /** Set of scale IDs that have been completed in this session */
  administeredScaleIds: Set<string>
  /** Red flags detected in the current session transcript. */
  detectedRedFlags: DetectedFlag[]
  /**
   * True once the AI Historian has signaled completion by calling
   * save_interview_output. Consumers can use this to auto-end the session
   * after the AI finishes its closing message.
   */
  interviewCompleted: boolean
}

const SAFETY_KEYWORDS = [
  'kill myself', 'want to die', 'hurt myself', 'end my life',
  'suicide', 'suicidal', 'self-harm', 'don\'t want to live',
  'hurt someone', 'kill someone',
]

/** How many patient turns between localizer runs. */
const LOCALIZER_INTERVAL = 3

export function useRealtimeSession(options: UseRealtimeSessionOptions): UseRealtimeSessionResult {
  const [status, setStatus] = useState<SessionStatus>('idle')
  const [transcript, setTranscript] = useState<HistorianTranscriptEntry[]>([])
  const [currentAssistantText, setCurrentAssistantText] = useState('')
  const [currentUserText, setCurrentUserText] = useState('')
  const [isAiSpeaking, setIsAiSpeaking] = useState(false)
  const [isUserSpeaking, setIsUserSpeaking] = useState(false)
  const [duration, setDuration] = useState(0)
  const [error, setError] = useState<string | null>(null)
  const [localizerData, setLocalizerData] = useState<LocalizerResponse | null>(null)
  const [localizerLoading, setLocalizerLoading] = useState(false)
  const [administeredScaleIds, setAdministeredScaleIds] = useState<Set<string>>(new Set())
  const [detectedRedFlags, setDetectedRedFlags] = useState<DetectedFlag[]>([])
  const [interviewCompleted, setInterviewCompleted] = useState(false)

  const pcRef = useRef<RTCPeerConnection | null>(null)
  const dcRef = useRef<RTCDataChannel | null>(null)
  const audioElRef = useRef<HTMLAudioElement | null>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const startTimeRef = useRef<number>(0)
  const questionCountRef = useRef<number>(0)
  const structuredOutputRef = useRef<HistorianStructuredOutput | null>(null)
  const narrativeSummaryRef = useRef<string | null>(null)
  const redFlagsRef = useRef<HistorianRedFlag[]>([])
  const safetyEscalatedRef = useRef<boolean>(false)
  const transcriptRef = useRef<HistorianTranscriptEntry[]>([])
  const administeredScaleIdsRef = useRef<Set<string>>(new Set())
  // Keep stable reference to options callbacks to avoid stale closures
  const onScaleCompleteRef = useRef(options.onScaleComplete)
  useEffect(() => { onScaleCompleteRef.current = options.onScaleComplete }, [options.onScaleComplete])

  // Localizer-specific refs
  const patientTurnCountRef = useRef<number>(0)
  const lastLocalizerTurnRef = useRef<number>(0)
  const localizerInFlightRef = useRef<boolean>(false)

  // Safety keyword check (secondary defense)
  const checkSafety = useCallback((text: string) => {
    const lower = text.toLowerCase()
    for (const kw of SAFETY_KEYWORDS) {
      if (lower.includes(kw)) {
        safetyEscalatedRef.current = true
        setStatus('safety_escalation')
        options.onSafetyEscalation?.()
        return true
      }
    }
    return false
  }, [options])

  const cleanup = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    if (dcRef.current) {
      try { dcRef.current.close() } catch {}
      dcRef.current = null
    }
    if (pcRef.current) {
      try { pcRef.current.close() } catch {}
      pcRef.current = null
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop())
      streamRef.current = null
    }
    if (audioElRef.current) {
      audioElRef.current.srcObject = null
      if (audioElRef.current.parentNode) {
        audioElRef.current.parentNode.removeChild(audioElRef.current)
      }
      audioElRef.current = null
    }
  }, [])

  // ── Localizer: fire async, inject guidance back into session ─────────
  const runLocalizer = useCallback(async () => {
    const localizerEnabled = options.enableLocalizer !== false // default true
    if (!localizerEnabled) return
    if (localizerInFlightRef.current) return
    if (transcriptRef.current.length < 2) return

    localizerInFlightRef.current = true
    setLocalizerLoading(true)

    // Grab last 8 turns for context
    const recentTurns = transcriptRef.current.slice(-8).map(t => ({
      role: t.role,
      text: t.text,
    }))

    try {
      const res = await fetch('/api/ai/historian/localizer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: options.consultId ?? 'ephemeral',
          sessionType: options.sessionType,
          transcript: recentTurns.map(t => ({
            ...t,
            timestamp: Date.now(),
          })),
          chiefComplaint: options.referralReason,
          referralReason: options.referralReason,
        }),
      })

      if (!res.ok) {
        // Non-2xx — log and continue; session is unaffected
        console.warn(`[localizer] HTTP ${res.status} — skipping this run`)
        return
      }

      const data: LocalizerResponse = await res.json()

      // Update state for physician panel
      setLocalizerData(data)
      options.onLocalizerUpdate?.(data)

      // Inject follow-up questions as advisory guidance into the session
      if (data.contextHint && dcRef.current?.readyState === 'open') {
        const guidance = `[Clinical guidance — advisory]: ${data.contextHint}`
        dcRef.current.send(JSON.stringify({
          type: 'conversation.item.create',
          item: {
            type: 'message',
            role: 'system',
            content: [{ type: 'input_text', text: guidance }],
          },
        }))
        // No response.create — advisory only; AI picks it up on its next natural turn
      }
    } catch (err: any) {
      // Network/timeout errors must not interrupt the session
      console.warn('[localizer] run failed (session continues):', err?.message)
    } finally {
      localizerInFlightRef.current = false
      setLocalizerLoading(false)
    }
  }, [options])

  const startSession = useCallback(async () => {
    setStatus('connecting')
    setError(null)
    setTranscript([])
    setCurrentAssistantText('')
    setCurrentUserText('')
    setLocalizerData(null)
    transcriptRef.current = []
    questionCountRef.current = 0
    structuredOutputRef.current = null
    narrativeSummaryRef.current = null
    redFlagsRef.current = []
    safetyEscalatedRef.current = false
    patientTurnCountRef.current = 0
    lastLocalizerTurnRef.current = 0
    localizerInFlightRef.current = false
    administeredScaleIdsRef.current = new Set()
    setAdministeredScaleIds(new Set())
    setDetectedRedFlags([])
    setInterviewCompleted(false)

    try {
      // 1. Get ephemeral token
      const tokenRes = await fetch('/api/ai/historian/session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionType: options.sessionType,
          referralReason: options.referralReason,
          patientContext: options.patientContext,
        }),
      })

      if (!tokenRes.ok) {
        const errData = await tokenRes.json().catch(() => ({}))
        throw new Error(errData.error || `Failed to get session token (${tokenRes.status})`)
      }

      const { ephemeralKey } = await tokenRes.json()
      if (!ephemeralKey) throw new Error('No ephemeral key returned')

      // 2. Create RTCPeerConnection
      const pc = new RTCPeerConnection()
      pcRef.current = pc

      // 3. Set up remote audio playback
      // iOS Safari requires the element to be attached to the DOM for audio
      // to route correctly (including to the phone's speaker). We hide it
      // visually but keep it in the tree.
      const audioEl = document.createElement('audio')
      audioEl.autoplay = true
      audioEl.controls = false
      // @ts-expect-error - playsinline is valid for iOS Safari
      audioEl.playsInline = true
      audioEl.style.display = 'none'
      audioEl.setAttribute('aria-hidden', 'true')
      document.body.appendChild(audioEl)
      audioElRef.current = audioEl

      pc.ontrack = (event) => {
        audioEl.srcObject = event.streams[0]
        // Ensure playback resumes if the browser paused after srcObject change.
        audioEl.play().catch(() => {})
      }

      // 4. Get user mic
      // Explicit constraints give the best behavior when users listen on
      // speakerphone — the mic will suppress the speaker bleed rather than
      // canceling the AI audio outright.
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: {
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: true,
        },
      })
      streamRef.current = stream
      stream.getTracks().forEach(track => pc.addTrack(track, stream))

      // 5. Create data channel for events
      const dc = pc.createDataChannel('oai-events')
      dcRef.current = dc

      dc.onopen = () => {
        // Session is connected, send initial response.create to kick things off
        dc.send(JSON.stringify({
          type: 'response.create',
          response: {
            modalities: ['text', 'audio'],
          },
        }))
      }

      dc.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data)
          handleServerEvent(msg)
        } catch {}
      }

      // 6. SDP offer
      const offer = await pc.createOffer()
      await pc.setLocalDescription(offer)

      // 7. Send offer to OpenAI, get answer
      const sdpRes = await fetch('https://api.openai.com/v1/realtime?model=gpt-realtime', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${ephemeralKey}`,
          'Content-Type': 'application/sdp',
        },
        body: offer.sdp,
      })

      if (!sdpRes.ok) {
        throw new Error(`WebRTC SDP exchange failed (${sdpRes.status})`)
      }

      const answerSdp = await sdpRes.text()
      await pc.setRemoteDescription({ type: 'answer', sdp: answerSdp })

      // 8. Start timer
      startTimeRef.current = Date.now()
      timerRef.current = setInterval(() => {
        setDuration(Math.floor((Date.now() - startTimeRef.current) / 1000))
      }, 1000)

      setStatus('active')
    } catch (err: any) {
      console.error('Failed to start realtime session:', err)
      setError(err.message || 'Failed to start session')
      setStatus('error')
      cleanup()
    }
  }, [options.sessionType, options.referralReason, options.patientContext, cleanup])

  // Handle server events from the data channel
  const handleServerEvent = useCallback((msg: any) => {
    switch (msg.type) {
      case 'response.audio_transcript.delta': {
        // Streaming AI text
        setCurrentAssistantText(prev => prev + (msg.delta || ''))
        setIsAiSpeaking(true)
        break
      }

      case 'response.audio_transcript.done': {
        // AI finished speaking this response
        const fullText = msg.transcript || ''
        if (fullText.trim()) {
          const entry: HistorianTranscriptEntry = {
            role: 'assistant',
            text: fullText.trim(),
            timestamp: Math.floor((Date.now() - startTimeRef.current) / 1000),
          }
          transcriptRef.current = [...transcriptRef.current, entry]
          setTranscript([...transcriptRef.current])
          questionCountRef.current += 1
        }
        setCurrentAssistantText('')
        setIsAiSpeaking(false)
        break
      }

      case 'conversation.item.input_audio_transcription.completed': {
        // User finished speaking
        const userText = msg.transcript || ''
        if (userText.trim()) {
          const entry: HistorianTranscriptEntry = {
            role: 'user',
            text: userText.trim(),
            timestamp: Math.floor((Date.now() - startTimeRef.current) / 1000),
          }
          transcriptRef.current = [...transcriptRef.current, entry]
          setTranscript([...transcriptRef.current])

          // Safety check on user speech
          checkSafety(userText)

          // Red flag detection: run keyword matching on cumulative transcript
          const fullText = transcriptRef.current
            .filter(t => t.role === 'user')
            .map(t => t.text)
            .join(' ')
          const detection = detectRedFlags(fullText, options.consultId ?? 'ephemeral')
          if (detection.detected_flags.length > 0) {
            setDetectedRedFlags(detection.detected_flags)
            options.onRedFlagDetected?.(detection.detected_flags)
          }

          // Localizer: increment patient turn counter and trigger every 3 turns
          patientTurnCountRef.current += 1
          const turnsSinceLast = patientTurnCountRef.current - lastLocalizerTurnRef.current
          if (turnsSinceLast >= LOCALIZER_INTERVAL) {
            lastLocalizerTurnRef.current = patientTurnCountRef.current
            // Fire async — must not block the event loop
            runLocalizer()
          }
        }
        setCurrentUserText('')
        setIsUserSpeaking(false)
        break
      }

      case 'input_audio_buffer.speech_started': {
        setIsUserSpeaking(true)
        setCurrentUserText('(listening...)')
        break
      }

      case 'input_audio_buffer.speech_stopped': {
        setIsUserSpeaking(false)
        break
      }

      case 'response.done': {
        // Check if the response includes tool calls
        const output = msg.response?.output
        if (output && Array.isArray(output)) {
          for (const item of output) {
            if (item.type !== 'function_call') continue

            // ── save_interview_output (existing) ──
            if (item.name === 'save_interview_output') {
              try {
                const args = JSON.parse(item.arguments || '{}')
                const { narrative_summary, red_flags, safety_escalated, ...structured } = args
                structuredOutputRef.current = structured
                narrativeSummaryRef.current = narrative_summary || null
                if (red_flags && Array.isArray(red_flags)) {
                  redFlagsRef.current = red_flags
                }
                if (safety_escalated) {
                  safetyEscalatedRef.current = true
                }
                // Signal to consumers that the interview has concluded so
                // they can auto-end the session after the AI's closing line.
                setInterviewCompleted(true)

                if (dcRef.current?.readyState === 'open') {
                  dcRef.current.send(JSON.stringify({
                    type: 'conversation.item.create',
                    item: {
                      type: 'function_call_output',
                      call_id: item.call_id,
                      output: JSON.stringify({ success: true }),
                    },
                  }))
                  dcRef.current.send(JSON.stringify({
                    type: 'response.create',
                    response: { modalities: ['text', 'audio'] },
                  }))
                }
              } catch (e) {
                console.error('Error parsing save_interview_output:', e)
              }
            }

            // ── save_scale_responses (Phase 3) ──
            if (item.name === 'save_scale_responses') {
              try {
                const args: SaveScaleResponsesArgs = JSON.parse(item.arguments || '{}')

                // Track which scales have been administered this session
                const updatedSet = new Set(administeredScaleIdsRef.current)
                updatedSet.add(args.scale_id)
                administeredScaleIdsRef.current = updatedSet
                setAdministeredScaleIds(new Set(updatedSet))

                // Notify parent so it can POST to /api/ai/historian/scales?action=submit
                onScaleCompleteRef.current?.(args)

                // Acknowledge so model can continue the intake interview
                if (dcRef.current?.readyState === 'open') {
                  dcRef.current.send(JSON.stringify({
                    type: 'conversation.item.create',
                    item: {
                      type: 'function_call_output',
                      call_id: item.call_id,
                      output: JSON.stringify({ success: true, recorded: args.scale_id }),
                    },
                  }))
                  dcRef.current.send(JSON.stringify({
                    type: 'response.create',
                    response: { modalities: ['text', 'audio'] },
                  }))
                }
              } catch (e) {
                console.error('Error parsing save_scale_responses:', e)
              }
            }
          }
        }
        break
      }

      case 'error': {
        console.error('Realtime API error:', msg.error)
        setError(msg.error?.message || 'Realtime API error')
        break
      }
    }
  }, [checkSafety, runLocalizer])

  /**
   * Injects scale administration instructions into the live session.
   * Sends a session.update event to update the model's system prompt,
   * then triggers a new AI response to begin asking scale questions.
   *
   * @param instructionBlock - The instruction text built by buildScaleAdministrationInstructions()
   */
  const injectScaleAdministration = useCallback((instructionBlock: string) => {
    if (dcRef.current?.readyState !== 'open') {
      console.warn('[useRealtimeSession] injectScaleAdministration: data channel not open')
      return
    }
    // Append the scale block to the current session instructions
    dcRef.current.send(JSON.stringify({
      type: 'session.update',
      session: {
        // The Realtime API appends this to the model's system context.
        // We set instructions to undefined so we only pass the delta.
        // In practice, we inject via a user-turn message to avoid clobbering the full prompt.
      },
    }))
    // Inject as a system message in the conversation context
    dcRef.current.send(JSON.stringify({
      type: 'conversation.item.create',
      item: {
        type: 'message',
        role: 'user',
        content: [
          {
            type: 'input_text',
            text: `[SYSTEM INSTRUCTION — SCALE ADMINISTRATION]\n${instructionBlock}\n[END SYSTEM INSTRUCTION]`,
          },
        ],
      },
    }))
    // Trigger the model to start asking scale questions
    dcRef.current.send(JSON.stringify({
      type: 'response.create',
      response: { modalities: ['text', 'audio'] },
    }))
  }, [])

  const endSession = useCallback(() => {
    setStatus('ending')

    const finalDuration = Math.floor((Date.now() - startTimeRef.current) / 1000)
    setDuration(finalDuration)

    cleanup()

    // Fire completion callback
    options.onComplete?.({
      structuredOutput: structuredOutputRef.current,
      narrativeSummary: narrativeSummaryRef.current,
      redFlags: redFlagsRef.current,
      safetyEscalated: safetyEscalatedRef.current,
      transcript: transcriptRef.current,
      duration: finalDuration,
      questionCount: questionCountRef.current,
    })

    setStatus('complete')
  }, [cleanup, options])

  // Clean up on unmount
  useEffect(() => {
    return () => {
      cleanup()
    }
  }, [cleanup])

  return {
    status,
    transcript,
    currentAssistantText,
    currentUserText,
    isAiSpeaking,
    isUserSpeaking,
    duration,
    error,
    localizerData,
    localizerLoading,
    startSession,
    endSession,
    injectScaleAdministration,
    administeredScaleIds,
    detectedRedFlags,
    interviewCompleted,
  }
}
