'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import type { HistorianTranscriptEntry, HistorianStructuredOutput, HistorianRedFlag, HistorianSessionType } from '@/lib/historianTypes'
import type { LocalizerResponse } from '@/lib/consult/localizer-types'
import type { SaveScaleResponsesArgs } from '@/lib/consult/scales'
import { detectRedFlags } from '@/lib/consult/red-flags/red-flag-detector'
import type { DetectedFlag } from '@/lib/consult/red-flags/red-flag-types'
import type { VoiceEvent, VoiceProvider } from '@/lib/voice/providerTypes'
import { selectProvider, makeProvider } from '@/lib/voice/selectProvider'

type SessionStatus = 'idle' | 'connecting' | 'active' | 'ending' | 'complete' | 'error' | 'safety_escalation'

interface UseRealtimeSessionOptions {
  sessionType: HistorianSessionType
  referralReason?: string
  patientName?: string
  patientContext?: string
  /**
   * Optional stable ID passed to the localizer for logging/tracing.
   * Typically a UUID generated by the parent before the session starts.
   */
  consultId?: string
  /**
   * Optional voice provider override ('nova' | 'openai'). When omitted, the
   * session route decides (VOICE_PROVIDER env, default 'openai') and its
   * `provider` field wins; this is only a client-side fallback/override —
   * see selectProvider().
   */
  provider?: 'nova' | 'openai'
  /**
   * Enable the mid-session localizer (default: true).
   * Set to false to disable entirely for testing or lightweight sessions.
   */
  enableLocalizer?: boolean
  /** Called when a new localizer result arrives. */
  onLocalizerUpdate?: (data: LocalizerResponse) => void
  /** Called when red flags are detected in patient speech. */
  onRedFlagDetected?: (flags: DetectedFlag[]) => void
  onSafetyEscalation?: () => void
  onComplete?: (data: {
    structuredOutput: HistorianStructuredOutput | null
    narrativeSummary: string | null
    redFlags: HistorianRedFlag[]
    safetyEscalated: boolean
    transcript: HistorianTranscriptEntry[]
    duration: number
    questionCount: number
    /**
     * True when the patient ended the interview before the AI naturally
     * called save_interview_output. Consumers should flag the intake as
     * partial in downstream UIs and reports.
     */
    endedEarly: boolean
  }) => void
  /** Called when the historian AI completes a scale administration via save_scale_responses tool */
  onScaleComplete?: (args: SaveScaleResponsesArgs) => void
}

interface UseRealtimeSessionResult {
  status: SessionStatus
  transcript: HistorianTranscriptEntry[]
  currentAssistantText: string
  currentUserText: string
  isAiSpeaking: boolean
  isUserSpeaking: boolean
  duration: number
  error: string | null
  /** Latest localizer result — null until the first run completes. */
  localizerData: LocalizerResponse | null
  /** True while a localizer run is in flight. */
  localizerLoading: boolean
  startSession: () => Promise<void>
  endSession: () => Promise<void>
  /**
   * Injects scale administration instructions into the live session as
   * advisory system text, then forces the model to respond immediately so it
   * begins asking the scale questions. No-op if the session is not active.
   */
  injectScaleAdministration: (instructionBlock: string) => void
  /**
   * Phase 5 of 2026-05-27 historian upgrade — push Localizer findings into
   * the live session. Called by EmbeddedHistorian after each Localizer run
   * completes. Non-fatal if push fails.
   */
  pushLocalizerContext: (payload: {
    top_differentials?: string[]
    suggested_next_question?: string | null
    suggested_scale_id?: string | null
    turn_count?: number
  }) => void
  /** Set of scale IDs that have been completed in this session */
  administeredScaleIds: Set<string>
  /** Red flags detected in the current session transcript. */
  detectedRedFlags: DetectedFlag[]
  /**
   * True once the AI Historian has signaled completion by calling
   * save_interview_output. Consumers can use this to auto-end the session
   * after the AI finishes its closing message.
   */
  interviewCompleted: boolean
}

const SAFETY_KEYWORDS = [
  'kill myself', 'want to die', 'hurt myself', 'end my life',
  'suicide', 'suicidal', 'self-harm', 'don\'t want to live',
  'hurt someone', 'kill someone',
]

/** How many patient turns between localizer runs. */
const LOCALIZER_INTERVAL = 3

export function useRealtimeSession(options: UseRealtimeSessionOptions): UseRealtimeSessionResult {
  const [status, setStatus] = useState<SessionStatus>('idle')
  const [transcript, setTranscript] = useState<HistorianTranscriptEntry[]>([])
  const [currentAssistantText, setCurrentAssistantText] = useState('')
  const [currentUserText, setCurrentUserText] = useState('')
  const [isAiSpeaking, setIsAiSpeaking] = useState(false)
  const [isUserSpeaking, setIsUserSpeaking] = useState(false)
  const [duration, setDuration] = useState(0)
  const [error, setError] = useState<string | null>(null)
  const [localizerData, setLocalizerData] = useState<LocalizerResponse | null>(null)
  const [localizerLoading, setLocalizerLoading] = useState(false)
  const [administeredScaleIds, setAdministeredScaleIds] = useState<Set<string>>(new Set())
  const [detectedRedFlags, setDetectedRedFlags] = useState<DetectedFlag[]>([])
  const [interviewCompleted, setInterviewCompleted] = useState(false)

  // The active VoiceProvider owns ALL transport (WebRTC peer / WS relay, mic,
  // audio playback, data channel). The hook never touches transport directly
  // — all clinical harness logic below stays exactly as it was pre-refactor.
  const providerRef = useRef<VoiceProvider | null>(null)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const startTimeRef = useRef<number>(0)
  const questionCountRef = useRef<number>(0)
  const structuredOutputRef = useRef<HistorianStructuredOutput | null>(null)
  const narrativeSummaryRef = useRef<string | null>(null)
  const redFlagsRef = useRef<HistorianRedFlag[]>([])
  const safetyEscalatedRef = useRef<boolean>(false)
  const transcriptRef = useRef<HistorianTranscriptEntry[]>([])
  const administeredScaleIdsRef = useRef<Set<string>>(new Set())
  // Phase 5: holds the base instructions returned by /api/ai/historian/session.
  // Used by pushLocalizerContext to re-serialize BASE_PROMPT + delta (OpenAI)
  // or as the closing-line-free source text (Nova has no overwrite primitive).
  const baseInstructionsRef = useRef<string>('')
  // Keep stable reference to options callbacks to avoid stale closures
  const onScaleCompleteRef = useRef(options.onScaleComplete)
  useEffect(() => { onScaleCompleteRef.current = options.onScaleComplete }, [options.onScaleComplete])
  useEffect(() => { interviewCompletedRef.current = interviewCompleted }, [interviewCompleted])

  // Stable ref to endSession so the provider's `disconnected` handler can call
  // the latest version without a circular useCallback dependency.
  const endSessionRef = useRef<() => Promise<void>>(async () => {})

  // One-shot finalize guard — whichever path fires first (manual end or a
  // transport drop) wins; the other no-ops. Prevents double-save to
  // /api/ai/historian/save.
  const finalizingRef = useRef<boolean>(false)

  // Monotonic session counter. Incremented in startSession; captured by the
  // `disconnected` handler registered for that session's provider instance.
  // If the counter has advanced by the time the handler fires, it belongs to
  // a stale session (e.g. an old provider's close event firing async after
  // cleanup() already ran) and must not call endSession on the new session.
  const sessionGenRef = useRef<number>(0)

  // Mirror of interviewCompleted state as a ref so event handlers can read
  // the latest value without stale closure issues (avoids React state timing
  // races in the assistantTranscript handler).
  const interviewCompletedRef = useRef<boolean>(false)
  const autoEndTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const sessionTypeRef = useRef<string>('new_patient')

  // Localizer-specific refs
  const patientTurnCountRef = useRef<number>(0)
  const lastLocalizerTurnRef = useRef<number>(0)
  const localizerInFlightRef = useRef<boolean>(false)

  // Safety keyword check (secondary defense)
  const checkSafety = useCallback((text: string) => {
    const lower = text.toLowerCase()
    for (const kw of SAFETY_KEYWORDS) {
      if (lower.includes(kw)) {
        safetyEscalatedRef.current = true
        setStatus('safety_escalation')
        options.onSafetyEscalation?.()
        return true
      }
    }
    return false
  }, [options])

  const cleanup = useCallback(() => {
    // Stop the duration timer + auto-end timer. Transport teardown is owned
    // by the provider (provider.stop()), invoked from endSession / unmount —
    // NOT here, mirroring the pre-refactor split between React-side cleanup
    // and transport-side cleanup.
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    if (autoEndTimerRef.current) {
      clearTimeout(autoEndTimerRef.current)
      autoEndTimerRef.current = null
    }
  }, [])

  // ── Localizer: fire async, inject guidance back into session ─────────
  const runLocalizer = useCallback(async () => {
    const localizerEnabled = options.enableLocalizer !== false // default true
    if (!localizerEnabled) return
    if (localizerInFlightRef.current) return
    if (transcriptRef.current.length < 2) return

    localizerInFlightRef.current = true
    setLocalizerLoading(true)

    // Grab last 8 turns for context
    const recentTurns = transcriptRef.current.slice(-8).map(t => ({
      role: t.role,
      text: t.text,
    }))

    try {
      const res = await fetch('/api/ai/historian/localizer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: options.consultId ?? 'ephemeral',
          sessionType: options.sessionType,
          transcript: recentTurns.map(t => ({
            ...t,
            timestamp: Date.now(),
          })),
          chiefComplaint: options.referralReason,
          referralReason: options.referralReason,
        }),
      })

      if (!res.ok) {
        // Non-2xx — log and continue; session is unaffected
        console.warn(`[localizer] HTTP ${res.status} — skipping this run`)
        return
      }

      const data: LocalizerResponse = await res.json()

      // Update state for physician panel
      setLocalizerData(data)
      options.onLocalizerUpdate?.(data)

      // Inject follow-up questions as advisory guidance into the session —
      // advisory only, no forced response; the AI picks it up on its next
      // natural turn (matches the pre-refactor data-channel form with no
      // response.create).
      if (data.contextHint && providerRef.current) {
        const guidance = `[Clinical guidance — advisory]: ${data.contextHint}`
        providerRef.current.injectSystemText(guidance)
      }
    } catch (err: any) {
      // Network/timeout errors must not interrupt the session
      console.warn('[localizer] run failed (session continues):', err?.message)
    } finally {
      localizerInFlightRef.current = false
      setLocalizerLoading(false)
    }
  }, [options])

  // ── Tool execution: same per-tool logic that lived in handleServerEvent's
  // response.done branch pre-refactor, now keyed off the normalized `toolCall`
  // VoiceEvent and replying via provider.sendToolResult instead of writing
  // function_call_output to the data channel directly.
  const handleToolCall = useCallback((toolName: string, toolUseId: string, input: unknown) => {
    const provider = providerRef.current
    const args: any = (input && typeof input === 'object') ? input : {}

    // ── save_interview_output (existing) ──
    if (toolName === 'save_interview_output') {
      try {
        const { narrative_summary, red_flags, safety_escalated, ...structured } = args
        structuredOutputRef.current = structured
        narrativeSummaryRef.current = narrative_summary || null
        if (red_flags && Array.isArray(red_flags)) {
          redFlagsRef.current = red_flags
        }
        if (safety_escalated) {
          safetyEscalatedRef.current = true
        }
        // Signal to consumers that the interview has concluded so they can
        // auto-end the session after the AI's closing line.
        setInterviewCompleted(true)
        // The OpenAI provider's sendToolResult issues its own response.create
        // after the ack (no modalities — #142) so the model speaks its
        // closing line; Nova self-triggers.
        provider?.sendToolResult(toolUseId, { success: true })
      } catch (e) {
        console.error('Error handling save_interview_output:', e)
      }
      return
    }

    // ── save_scale_responses (Phase 3 — legacy, still handled if referenced) ──
    if (toolName === 'save_scale_responses') {
      try {
        const scaleArgs: SaveScaleResponsesArgs = args

        // Track which scales have been administered this session
        const updatedSet = new Set(administeredScaleIdsRef.current)
        updatedSet.add(scaleArgs.scale_id)
        administeredScaleIdsRef.current = updatedSet
        setAdministeredScaleIds(new Set(updatedSet))

        // Notify parent so it can POST to /api/ai/historian/scales?action=submit
        onScaleCompleteRef.current?.(scaleArgs)

        // Acknowledge so model can continue the intake interview
        provider?.sendToolResult(toolUseId, { success: true, recorded: scaleArgs.scale_id })
      } catch (e) {
        console.error('Error handling save_scale_responses:', e)
      }
      return
    }

    // ── scale_step (Phase 4 — paginated single-item admin) ──
    // Each call returns exactly one scale item from the server; the model
    // recites it verbatim, awaits the patient response, then calls scale_step
    // again with prev_response. Final call returns {done:true, total_score, ...}.
    if (toolName === 'scale_step') {
      ;(async () => {
        try {
          const res = await fetch('/api/ai/historian/scales?action=step', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              scale_id: args.scale_id,
              reason: args.reason,
              prev_index: args.prev_index,
              prev_response: args.prev_response,
              // consult_id is the session-scope key for in-progress
              // scale_results lookups. historian_session_id has a strict FK to
              // historian_sessions and is populated server-side when the
              // in-progress row gets backfilled.
              consult_id: options.consultId ?? undefined,
            }),
          })
          const result = await res.json()

          // If the scale just completed, mark it administered and notify the
          // parent (replaces the old save_scale_responses notify path).
          if (result?.done === true && typeof args.scale_id === 'string') {
            const updatedSet = new Set(administeredScaleIdsRef.current)
            updatedSet.add(args.scale_id)
            administeredScaleIdsRef.current = updatedSet
            setAdministeredScaleIds(new Set(updatedSet))
            onScaleCompleteRef.current?.({
              scale_id: args.scale_id,
              responses: {}, // raw_responses live server-side now
              total_score: result.total_score,
              interpretation: result.interpretation,
              severity_level: result.severity_level,
            } as any)
          }

          providerRef.current?.sendToolResult(toolUseId, result)
        } catch (err) {
          console.error('[useRealtimeSession] scale_step handler error:', err)
          providerRef.current?.sendToolResult(toolUseId, { status: 'error', message: 'client error' })
        }
      })()
      return
    }

    // ── query_evidence (Phase 3) ──
    if (toolName === 'query_evidence') {
      ;(async () => {
        try {
          const res = await fetch('/api/ai/historian/evidence-query', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              question: args.question,
              focus_diagnoses: args.focus_diagnoses,
            }),
          })
          const result = await res.json()
          providerRef.current?.sendToolResult(toolUseId, result)
        } catch (err) {
          console.error('[useRealtimeSession] query_evidence handler error:', err)
          providerRef.current?.sendToolResult(toolUseId, { status: 'error', chunks: [], message: 'client error' })
        }
      })()
      return
    }
  }, [options.consultId])

  // ── Normalized provider event handler — replaces handleServerEvent.
  // Routes provider-agnostic VoiceEvents to the SAME harness logic as before
  // the provider-abstraction refactor.
  const handleVoiceEvent = useCallback((e: VoiceEvent, sessionGen: number) => {
    switch (e.type) {
      case 'assistantTextDelta': {
        // Streaming AI text (was response.audio_transcript.delta)
        setCurrentAssistantText(prev => prev + (e.text || ''))
        setIsAiSpeaking(true)
        break
      }

      case 'assistantTranscript': {
        // AI finished speaking this response (was response.audio_transcript.done)
        const fullText = e.text || ''
        if (fullText.trim()) {
          const entry: HistorianTranscriptEntry = {
            role: 'assistant',
            text: fullText.trim(),
            timestamp: Math.floor((Date.now() - startTimeRef.current) / 1000),
          }
          transcriptRef.current = [...transcriptRef.current, entry]
          setTranscript([...transcriptRef.current])
          questionCountRef.current += 1
        }
        setCurrentAssistantText('')
        setIsAiSpeaking(false)

        // #143: if save_interview_output already fired, this audio is the
        // closing message. Schedule auto-end now that the AI has finished
        // speaking — via a ref so this handler never has a stale closure on
        // endSessionRef.
        if (interviewCompletedRef.current && !finalizingRef.current) {
          if (autoEndTimerRef.current) clearTimeout(autoEndTimerRef.current)
          autoEndTimerRef.current = setTimeout(() => {
            endSessionRef.current()
          }, 0)
        }
        break
      }

      case 'userTranscript': {
        // User finished speaking (was input_audio_transcription.completed)
        const userText = e.text || ''
        if (userText.trim()) {
          const entry: HistorianTranscriptEntry = {
            role: 'user',
            text: userText.trim(),
            timestamp: Math.floor((Date.now() - startTimeRef.current) / 1000),
          }
          transcriptRef.current = [...transcriptRef.current, entry]
          setTranscript([...transcriptRef.current])

          // Safety check on user speech
          checkSafety(userText)

          // Red flag detection: run keyword matching on cumulative transcript
          const fullText = transcriptRef.current
            .filter(t => t.role === 'user')
            .map(t => t.text)
            .join(' ')
          const detection = detectRedFlags(fullText, options.consultId ?? 'ephemeral')
          if (detection.detected_flags.length > 0) {
            setDetectedRedFlags(detection.detected_flags)
            options.onRedFlagDetected?.(detection.detected_flags)
          }

          // Localizer: increment patient turn counter and trigger every 3 turns
          patientTurnCountRef.current += 1
          const turnsSinceLast = patientTurnCountRef.current - lastLocalizerTurnRef.current
          if (turnsSinceLast >= LOCALIZER_INTERVAL) {
            lastLocalizerTurnRef.current = patientTurnCountRef.current
            // Fire async — must not block the event loop
            runLocalizer()
          }
        }
        setCurrentUserText('')
        setIsUserSpeaking(false)
        break
      }

      case 'userSpeechStart': {
        // NOTE: emitted only by the OpenAI provider (input_audio_buffer.
        // speech_started). Nova does not forward user-speech VAD boundaries, so
        // under Nova isUserSpeaking stays false — best-effort indicator only.
        setIsUserSpeaking(true)
        setCurrentUserText('(listening...)')
        break
      }

      case 'userSpeechStop': {
        setIsUserSpeaking(false)
        break
      }

      case 'aiSpeechStart': {
        setIsAiSpeaking(true)
        break
      }

      case 'aiSpeechStop': {
        setIsAiSpeaking(false)
        break
      }

      case 'toolCall': {
        handleToolCall(e.toolName, e.toolUseId, e.input)
        break
      }

      case 'disconnected': {
        // Transport dropped unexpectedly (WebRTC failed/closed, WS closed
        // non-cleanly). Ignore stale handlers from a previous session (e.g. a
        // close event racing async after cleanup() already ran for a NEWER
        // session) — mirrors the pre-refactor handleDrop's sessionGen check.
        if (sessionGenRef.current !== sessionGen) break
        console.warn('[useRealtimeSession] transport disconnected —', e.reason, '— running graceful end')
        endSessionRef.current()
        break
      }

      case 'error': {
        console.error('Voice provider error:', e.message)
        setError(e.message || 'Voice provider error')
        break
      }
    }
  }, [checkSafety, runLocalizer, handleToolCall, options])

  const startSession = useCallback(async () => {
    setStatus('connecting')
    setError(null)
    setTranscript([])
    setCurrentAssistantText('')
    setCurrentUserText('')
    setLocalizerData(null)
    transcriptRef.current = []
    questionCountRef.current = 0
    structuredOutputRef.current = null
    narrativeSummaryRef.current = null
    redFlagsRef.current = []
    safetyEscalatedRef.current = false
    patientTurnCountRef.current = 0
    lastLocalizerTurnRef.current = 0
    localizerInFlightRef.current = false
    administeredScaleIdsRef.current = new Set()
    setAdministeredScaleIds(new Set())
    setDetectedRedFlags([])
    setInterviewCompleted(false)
    interviewCompletedRef.current = false
    finalizingRef.current = false
    if (autoEndTimerRef.current) {
      clearTimeout(autoEndTimerRef.current)
      autoEndTimerRef.current = null
    }
    const sessionGen = ++sessionGenRef.current

    try {
      // 1. Fetch provider config from the session route. The route returns
      //    provider-native config: for OpenAI an ephemeral key + tools; for
      //    Nova a relayUrl + voiceId + Nova-shaped tools.
      const tokenRes = await fetch('/api/ai/historian/session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionType: options.sessionType,
          referralReason: options.referralReason,
          patientContext: options.patientContext,
          provider: options.provider,
        }),
      })

      if (!tokenRes.ok) {
        const errData = await tokenRes.json().catch(() => ({}))
        throw new Error(errData.error || `Failed to get session token (${tokenRes.status})`)
      }

      const sessionConfig = await tokenRes.json()
      const {
        ephemeralKey,
        model: sessionModel,
        base_instructions: sessionBaseInstructions,
        instructions: sessionInstructions,
        tools: sessionTools,
        voiceId,
        relayUrl,
        expiresAt,
      } = sessionConfig

      // 2. Resolve the provider kind. The route's `provider` field wins (it
      //    minted the session for that kind); fall back to selectProvider
      //    (defaults to 'openai') with our optional override.
      const kind: 'nova' | 'openai' =
        sessionConfig.provider === 'openai' || sessionConfig.provider === 'nova'
          ? sessionConfig.provider
          : selectProvider(options.provider)

      // OpenAI requires the ephemeral key; Nova does not.
      if (kind === 'openai' && !ephemeralKey) throw new Error('No ephemeral key returned')

      // Store sessionType for renewal requests.
      sessionTypeRef.current = options.sessionType ?? 'new_patient'

      // Phase 5: store the resolved base instructions so pushLocalizerContext
      // can re-serialize BASE_PROMPT + delta (OpenAI) or inject advisory text
      // (Nova).
      baseInstructionsRef.current = sessionBaseInstructions ?? sessionInstructions ?? ''

      // 3. Instantiate the provider and wire the single normalized event sink.
      const provider = makeProvider(kind)
      providerRef.current = provider
      provider.on((e) => handleVoiceEvent(e, sessionGen))

      // 4. Open the transport. The provider ignores fields it doesn't need
      //    (OpenAI ignores relayUrl; Nova ignores ephemeralKey/model/expiresAt).
      await provider.start({
        instructions: baseInstructionsRef.current,
        tools: sessionTools ?? [],
        voiceId,
        ephemeralKey,
        model: sessionModel,
        relayUrl,
        expiresAt,
        sessionType: sessionTypeRef.current,
      })

      // 5. Start timer
      startTimeRef.current = Date.now()
      timerRef.current = setInterval(() => {
        setDuration(Math.floor((Date.now() - startTimeRef.current) / 1000))
      }, 1000)

      setStatus('active')
    } catch (err: any) {
      console.error('Failed to start realtime session:', err)
      setError(err.message || 'Failed to start session')
      setStatus('error')
      cleanup()
      // Tear down any half-open transport the provider may have allocated.
      try { await providerRef.current?.stop() } catch {}
      providerRef.current = null
    }
  }, [
    options.sessionType,
    options.referralReason,
    options.patientContext,
    options.consultId,
    options.provider,
    cleanup,
    handleVoiceEvent,
  ])

  /**
   * Phase 5 of 2026-05-27 historian upgrade — Localizer push channel.
   *
   * Called after each Localizer pipeline run completes (every ~3 turns).
   *
   * OpenAI: re-serializes BASE_PROMPT + latest delta via
   * provider.updateInstructions (session.update), OVERWRITING the
   * instructions field so only the latest delta stays active — preserves the
   * exact pre-refactor mechanism (no timeline pollution from accumulating
   * role:"system" messages).
   *
   * Nova: has no instructions-overwrite primitive (a second SYSTEM block is
   * rejected), so the delta is delivered as an advisory user-turn via
   * injectSystemText, framed explicitly as private/physician-only context the
   * model must not speak aloud or name to the patient.
   *
   * Non-fatal: if the push fails, the interview continues on the prior
   * instructions. No retries.
   */
  const pushLocalizerContext = useCallback(
    (pushPayload: {
      top_differentials?: string[]
      suggested_next_question?: string | null
      suggested_scale_id?: string | null
      turn_count?: number
    }) => {
      const provider = providerRef.current
      if (!provider) return

      try {
        if (provider.updateInstructions) {
          // OpenAI path — unchanged from before the provider-abstraction refactor.
          if (!baseInstructionsRef.current) return
          const delta = [
            `[LATEST LOCALIZER PUSH${pushPayload.turn_count != null ? ` @ turn ${pushPayload.turn_count}` : ''}]`,
            `- Top differentials: ${(pushPayload.top_differentials ?? []).join(', ') || '(none yet)'}`,
            `- Suggested next question: ${pushPayload.suggested_next_question ?? '(none)'}`,
            `- Suggested scale to consider: ${pushPayload.suggested_scale_id ?? '(none)'}`,
          ].join('\n')
          const updatedInstructions = baseInstructionsRef.current + '\n\n' + delta
          provider.updateInstructions(updatedInstructions)
        } else {
          // Nova path — advisory user-turn injection, explicitly framed as
          // private/physician-only so the model never speaks it or names a
          // condition to the patient.
          const delta = [
            `[INTERNAL CLINICAL NOTE — system-generated, NOT spoken by the patient. Do NOT read this aloud, do NOT mention these possible diagnoses, and do NOT name any condition to the patient. Use it ONLY to choose which symptoms to ask about next, phrased in plain everyday language.]`,
            `[Localizer update${pushPayload.turn_count != null ? ` @ turn ${pushPayload.turn_count}` : ''}]`,
            `- Differentials under consideration (physician-facing — keep private): ${(pushPayload.top_differentials ?? []).join(', ') || '(none yet)'}`,
            `- Suggested angle for your next plain-language question: ${pushPayload.suggested_next_question ?? '(none)'}`,
            `- Suggested scale to consider (do not name it to the patient): ${pushPayload.suggested_scale_id ?? '(none)'}`,
          ].join('\n')
          provider.injectSystemText(delta)
        }
      } catch (err) {
        console.error('[useRealtimeSession] pushLocalizerContext failed:', err)
        // Non-fatal — interview continues on previous instructions
      }
    },
    [],
  )

  /**
   * Injects scale administration instructions into the live session as advisory
   * system text, then forces the model to respond so it begins asking the scale
   * questions. Composes injectSystemText + requestResponse (the shared way to
   * express the old "inject + response.create" pattern across providers).
   */
  const injectScaleAdministration = useCallback((instructionBlock: string) => {
    const provider = providerRef.current
    if (!provider) {
      console.warn('[useRealtimeSession] injectScaleAdministration: no active session')
      return
    }
    provider.injectSystemText(
      `[SYSTEM INSTRUCTION — SCALE ADMINISTRATION]\n${instructionBlock}\n[END SYSTEM INSTRUCTION]`,
    )
    // Force the model to start asking scale questions now.
    provider.requestResponse()
  }, [])

  const endSession = useCallback(async () => {
    if (finalizingRef.current) return
    finalizingRef.current = true
    setStatus('ending')

    const finalDuration = Math.floor((Date.now() - startTimeRef.current) / 1000)
    setDuration(finalDuration)

    const provider = providerRef.current

    // If the AI never called save_interview_output but the patient has had a
    // real conversation, nudge it to save before we tear the transport down.
    // Without this, ending early (manual "End Interview" click, or an
    // unexpected transport drop) silently drops the entire intake — both the
    // structured output and the narrative summary — and the review step shows
    // "No interview data available" despite the patient answering questions.
    const needsFlush =
      !structuredOutputRef.current &&
      transcriptRef.current.length >= 2 &&
      !!provider

    if (needsFlush && provider) {
      try {
        provider.injectSystemText(
          'The patient has ended the interview early. Immediately call the save_interview_output tool with whatever information has been gathered so far. Populate narrative_summary with a concise summary of the conversation. Do not ask any more questions and do not speak — just call the tool.',
        )
        // Text-only forced response — the interview is ending, so we don't
        // want the AI to speak a full audio reply right before teardown.
        provider.requestResponse({ textOnly: true })

        const deadline = Date.now() + 4000
        while (!structuredOutputRef.current && Date.now() < deadline) {
          await new Promise(r => setTimeout(r, 100))
        }
      } catch (err) {
        console.warn('[useRealtimeSession] flush save prompt failed:', err)
      }
    }

    // Last-resort fallback: if the AI still hasn't produced a narrative (tool
    // didn't fire, channel dropped, model refused, etc.), preserve the raw
    // transcript as the narrative summary so the physician can still see what
    // the patient said.
    if (!narrativeSummaryRef.current && transcriptRef.current.length > 0) {
      const hasPatientSpeech = transcriptRef.current.some(
        t => t.role === 'user' && t.text.trim().length > 0,
      )
      if (hasPatientSpeech) {
        narrativeSummaryRef.current =
          'Interview ended before AI generated a structured summary. Raw transcript:\n\n' +
          transcriptRef.current
            .map(t => `${t.role === 'assistant' ? 'AI' : 'Patient'}: ${t.text}`)
            .join('\n\n')
      }
    }

    // Stop the timer, then tear the transport down via the provider.
    cleanup()
    try { await provider?.stop() } catch {}
    providerRef.current = null

    // `interviewCompleted` flips to true only when the AI called
    // save_interview_output. If it never fired, the patient ended before the
    // AI judged the intake complete — flag it as partial.
    const endedEarly = !interviewCompleted

    options.onComplete?.({
      structuredOutput: structuredOutputRef.current,
      narrativeSummary: narrativeSummaryRef.current,
      redFlags: redFlagsRef.current,
      safetyEscalated: safetyEscalatedRef.current,
      transcript: transcriptRef.current,
      duration: finalDuration,
      questionCount: questionCountRef.current,
      endedEarly,
    })

    setStatus('complete')
  }, [cleanup, options, interviewCompleted])

  // Keep the ref in sync so the provider's `disconnected` handler always
  // calls the latest endSession.
  useEffect(() => { endSessionRef.current = endSession }, [endSession])

  // Clean up on unmount
  useEffect(() => {
    return () => {
      cleanup()
      // Best-effort transport teardown on unmount.
      try { providerRef.current?.stop() } catch {}
      providerRef.current = null
    }
  }, [cleanup])

  return {
    status,
    transcript,
    currentAssistantText,
    currentUserText,
    isAiSpeaking,
    isUserSpeaking,
    duration,
    error,
    localizerData,
    localizerLoading,
    startSession,
    endSession,
    injectScaleAdministration,
    pushLocalizerContext,
    administeredScaleIds,
    detectedRedFlags,
    interviewCompleted,
  }
}
