'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import type { HistorianTranscriptEntry, HistorianStructuredOutput, HistorianRedFlag, HistorianSessionType } from '@/lib/historianTypes'
import type { LocalizerResponse } from '@/lib/consult/localizer-types'
import type { SaveScaleResponsesArgs } from '@/lib/consult/scales'
import { detectRedFlags } from '@/lib/consult/red-flags/red-flag-detector'
import type { DetectedFlag } from '@/lib/consult/red-flags/red-flag-types'

type SessionStatus = 'idle' | 'connecting' | 'active' | 'ending' | 'complete' | 'error' | 'safety_escalation'

interface UseRealtimeSessionOptions {
  sessionType: HistorianSessionType
  referralReason?: string
  patientName?: string
  patientContext?: string
  /**
   * Optional stable ID passed to the localizer for logging/tracing.
   * Typically a UUID generated by the parent before the session starts.
   */
  consultId?: string
  /**
   * Enable the mid-session localizer (default: true).
   * Set to false to disable entirely for testing or lightweight sessions.
   */
  enableLocalizer?: boolean
  /** Called when a new localizer result arrives. */
  onLocalizerUpdate?: (data: LocalizerResponse) => void
  /** Called when red flags are detected in patient speech. */
  onRedFlagDetected?: (flags: DetectedFlag[]) => void
  onSafetyEscalation?: () => void
  onComplete?: (data: {
    structuredOutput: HistorianStructuredOutput | null
    narrativeSummary: string | null
    redFlags: HistorianRedFlag[]
    safetyEscalated: boolean
    transcript: HistorianTranscriptEntry[]
    duration: number
    questionCount: number
    /**
     * True when the patient ended the interview before the AI naturally
     * called save_interview_output. Consumers should flag the intake as
     * partial in downstream UIs and reports.
     */
    endedEarly: boolean
  }) => void
  /** Called when the historian AI completes a scale administration via save_scale_responses tool */
  onScaleComplete?: (args: SaveScaleResponsesArgs) => void
}

interface UseRealtimeSessionResult {
  status: SessionStatus
  transcript: HistorianTranscriptEntry[]
  currentAssistantText: string
  currentUserText: string
  isAiSpeaking: boolean
  isUserSpeaking: boolean
  duration: number
  error: string | null
  /** Latest localizer result — null until the first run completes. */
  localizerData: LocalizerResponse | null
  /** True while a localizer run is in flight. */
  localizerLoading: boolean
  startSession: () => Promise<void>
  endSession: () => Promise<void>
  /**
   * Injects scale administration instructions into the live session by sending
   * a session.update event on the data channel, then triggering a new response.
   * No-op if the session is not active or the data channel is closed.
   */
  injectScaleAdministration: (instructionBlock: string) => void
  /**
   * Phase 5 of 2026-05-27 historian upgrade — push Localizer findings into
   * the live session as a re-serialized instructions delta. Called by
   * EmbeddedHistorian after each Localizer run completes. Non-fatal if push
   * fails.
   */
  pushLocalizerContext: (payload: {
    top_differentials?: string[]
    suggested_next_question?: string | null
    suggested_scale_id?: string | null
    turn_count?: number
  }) => void
  /** Set of scale IDs that have been completed in this session */
  administeredScaleIds: Set<string>
  /** Red flags detected in the current session transcript. */
  detectedRedFlags: DetectedFlag[]
  /**
   * True once the AI Historian has signaled completion by calling
   * save_interview_output. Consumers can use this to auto-end the session
   * after the AI finishes its closing message.
   */
  interviewCompleted: boolean
}

const SAFETY_KEYWORDS = [
  'kill myself', 'want to die', 'hurt myself', 'end my life',
  'suicide', 'suicidal', 'self-harm', 'don\'t want to live',
  'hurt someone', 'kill someone',
]

/** How many patient turns between localizer runs. */
const LOCALIZER_INTERVAL = 3

export function useRealtimeSession(options: UseRealtimeSessionOptions): UseRealtimeSessionResult {
  const [status, setStatus] = useState<SessionStatus>('idle')
  const [transcript, setTranscript] = useState<HistorianTranscriptEntry[]>([])
  const [currentAssistantText, setCurrentAssistantText] = useState('')
  const [currentUserText, setCurrentUserText] = useState('')
  const [isAiSpeaking, setIsAiSpeaking] = useState(false)
  const [isUserSpeaking, setIsUserSpeaking] = useState(false)
  const [duration, setDuration] = useState(0)
  const [error, setError] = useState<string | null>(null)
  const [localizerData, setLocalizerData] = useState<LocalizerResponse | null>(null)
  const [localizerLoading, setLocalizerLoading] = useState(false)
  const [administeredScaleIds, setAdministeredScaleIds] = useState<Set<string>>(new Set())
  const [detectedRedFlags, setDetectedRedFlags] = useState<DetectedFlag[]>([])
  const [interviewCompleted, setInterviewCompleted] = useState(false)

  const pcRef = useRef<RTCPeerConnection | null>(null)
  const dcRef = useRef<RTCDataChannel | null>(null)
  const audioElRef = useRef<HTMLAudioElement | null>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const startTimeRef = useRef<number>(0)
  const questionCountRef = useRef<number>(0)
  const structuredOutputRef = useRef<HistorianStructuredOutput | null>(null)
  const narrativeSummaryRef = useRef<string | null>(null)
  const redFlagsRef = useRef<HistorianRedFlag[]>([])
  const safetyEscalatedRef = useRef<boolean>(false)
  const transcriptRef = useRef<HistorianTranscriptEntry[]>([])
  const administeredScaleIdsRef = useRef<Set<string>>(new Set())
  // Phase 5: holds the base instructions returned by /api/ai/historian/session.
  // Used by pushLocalizerContext to re-serialize BASE_PROMPT + delta when
  // emitting session.update on the data channel every ~3 turns.
  const baseInstructionsRef = useRef<string>('')
  // Keep stable reference to options callbacks to avoid stale closures
  const onScaleCompleteRef = useRef(options.onScaleComplete)
  useEffect(() => { onScaleCompleteRef.current = options.onScaleComplete }, [options.onScaleComplete])
  useEffect(() => { interviewCompletedRef.current = interviewCompleted }, [interviewCompleted])

  // Stable ref to endSession so startSession's drop handlers can call the
  // latest version without a circular useCallback dependency.
  const endSessionRef = useRef<() => Promise<void>>(async () => {})

  // One-shot finalize guard — whichever path fires first (manual end or drop)
  // wins; the other no-ops. Prevents double-save to /api/ai/historian/save.
  const finalizingRef = useRef<boolean>(false)

  // Monotonic session counter. Incremented in startSession; captured by each
  // session's drop handlers (dc.onclose, pc.onconnectionstatechange). If the
  // counter has advanced by the time the handler fires, it belongs to a stale
  // session (e.g. dc.onclose firing async after cleanup() already ran) and
  // must not call endSession on the new session.
  const sessionGenRef = useRef<number>(0)

  // Set to true when session.created arrives. Used by dc.onopen to fire the
  // greeting response.create in case session.created beat the channel open.
  const sessionCreatedRef = useRef<boolean>(false)

  // Mirror of interviewCompleted state as a ref so event handlers can read
  // the latest value without stale closure issues (avoids React state timing
  // races in response.audio_transcript.done).
  const interviewCompletedRef = useRef<boolean>(false)
  const autoEndTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Session renewal — fires ~90 s before the ephemeral token expires so the
  // client swaps the credential without tearing down the WebRTC connection.
  const renewalTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const sessionTypeRef = useRef<string>('new_patient')

  // Localizer-specific refs
  const patientTurnCountRef = useRef<number>(0)
  const lastLocalizerTurnRef = useRef<number>(0)
  const localizerInFlightRef = useRef<boolean>(false)

  // Safety keyword check (secondary defense)
  const checkSafety = useCallback((text: string) => {
    const lower = text.toLowerCase()
    for (const kw of SAFETY_KEYWORDS) {
      if (lower.includes(kw)) {
        safetyEscalatedRef.current = true
        setStatus('safety_escalation')
        options.onSafetyEscalation?.()
        return true
      }
    }
    return false
  }, [options])

  const scheduleRenewal = useCallback((expiresAt: number) => {
    if (renewalTimerRef.current) clearTimeout(renewalTimerRef.current)
    const msUntilExpiry = expiresAt * 1000 - Date.now()
    const msUntilRenew = Math.max(msUntilExpiry - 90_000, 0) // 90 s before expiry
    console.log(`[useRealtimeSession] scheduling token renewal in ${Math.round(msUntilRenew / 1000)}s`)
    renewalTimerRef.current = setTimeout(async () => {
      if (!pcRef.current || !dcRef.current || dcRef.current.readyState !== 'open') return
      try {
        const res = await fetch('/api/ai/historian/session-renew', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ sessionType: sessionTypeRef.current }),
        })
        if (!res.ok) {
          console.warn('[useRealtimeSession] session-renew failed:', res.status)
          return
        }
        const { ephemeralKey, expiresAt: newExpiresAt } = await res.json()
        if (!ephemeralKey) return
        // Attempt to swap the credential via session.update.
        // TODO: verify whether OpenAI Realtime actually accepts client_secret
        // on session.update (the ephemeral key authenticates SDP setup, not
        // per-event config). If the 8-min cap is a hard session-duration limit
        // rather than token TTL, this send will be a no-op and the
        // onconnectionstatechange handler will catch the drop gracefully.
        dcRef.current!.send(JSON.stringify({
          type: 'session.update',
          session: { client_secret: ephemeralKey },
        }))
        console.log('[useRealtimeSession] token renewed — session continues')
        // Schedule the next renewal for the new token
        if (newExpiresAt) scheduleRenewal(newExpiresAt)
      } catch (err) {
        console.warn('[useRealtimeSession] session renewal error (non-fatal):', err)
      }
    }, msUntilRenew)
  }, [])

  const cleanup = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    if (renewalTimerRef.current) {
      clearTimeout(renewalTimerRef.current)
      renewalTimerRef.current = null
    }
    if (autoEndTimerRef.current) {
      clearTimeout(autoEndTimerRef.current)
      autoEndTimerRef.current = null
    }
    if (dcRef.current) {
      try { dcRef.current.close() } catch {}
      dcRef.current = null
    }
    if (pcRef.current) {
      try { pcRef.current.close() } catch {}
      pcRef.current = null
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop())
      streamRef.current = null
    }
    if (audioElRef.current) {
      audioElRef.current.srcObject = null
      if (audioElRef.current.parentNode) {
        audioElRef.current.parentNode.removeChild(audioElRef.current)
      }
      audioElRef.current = null
    }
  }, [])

  // ── Localizer: fire async, inject guidance back into session ─────────
  const runLocalizer = useCallback(async () => {
    const localizerEnabled = options.enableLocalizer !== false // default true
    if (!localizerEnabled) return
    if (localizerInFlightRef.current) return
    if (transcriptRef.current.length < 2) return

    localizerInFlightRef.current = true
    setLocalizerLoading(true)

    // Grab last 8 turns for context
    const recentTurns = transcriptRef.current.slice(-8).map(t => ({
      role: t.role,
      text: t.text,
    }))

    try {
      const res = await fetch('/api/ai/historian/localizer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: options.consultId ?? 'ephemeral',
          sessionType: options.sessionType,
          transcript: recentTurns.map(t => ({
            ...t,
            timestamp: Date.now(),
          })),
          chiefComplaint: options.referralReason,
          referralReason: options.referralReason,
        }),
      })

      if (!res.ok) {
        // Non-2xx — log and continue; session is unaffected
        console.warn(`[localizer] HTTP ${res.status} — skipping this run`)
        return
      }

      const data: LocalizerResponse = await res.json()

      // Update state for physician panel
      setLocalizerData(data)
      options.onLocalizerUpdate?.(data)

      // Inject follow-up questions as advisory guidance into the session
      if (data.contextHint && dcRef.current?.readyState === 'open') {
        const guidance = `[Clinical guidance — advisory]: ${data.contextHint}`
        dcRef.current.send(JSON.stringify({
          type: 'conversation.item.create',
          item: {
            type: 'message',
            role: 'system',
            content: [{ type: 'input_text', text: guidance }],
          },
        }))
        // No response.create — advisory only; AI picks it up on its next natural turn
      }
    } catch (err: any) {
      // Network/timeout errors must not interrupt the session
      console.warn('[localizer] run failed (session continues):', err?.message)
    } finally {
      localizerInFlightRef.current = false
      setLocalizerLoading(false)
    }
  }, [options])

  const startSession = useCallback(async () => {
    setStatus('connecting')
    setError(null)
    setTranscript([])
    setCurrentAssistantText('')
    setCurrentUserText('')
    setLocalizerData(null)
    transcriptRef.current = []
    questionCountRef.current = 0
    structuredOutputRef.current = null
    narrativeSummaryRef.current = null
    redFlagsRef.current = []
    safetyEscalatedRef.current = false
    patientTurnCountRef.current = 0
    lastLocalizerTurnRef.current = 0
    localizerInFlightRef.current = false
    administeredScaleIdsRef.current = new Set()
    setAdministeredScaleIds(new Set())
    setDetectedRedFlags([])
    setInterviewCompleted(false)
    interviewCompletedRef.current = false
    finalizingRef.current = false
    if (autoEndTimerRef.current) {
      clearTimeout(autoEndTimerRef.current)
      autoEndTimerRef.current = null
    }
    sessionCreatedRef.current = false
    const sessionGen = ++sessionGenRef.current

    try {
      // 1. Get ephemeral token
      const tokenRes = await fetch('/api/ai/historian/session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionType: options.sessionType,
          referralReason: options.referralReason,
          patientContext: options.patientContext,
        }),
      })

      if (!tokenRes.ok) {
        const errData = await tokenRes.json().catch(() => ({}))
        throw new Error(errData.error || `Failed to get session token (${tokenRes.status})`)
      }

      const {
        ephemeralKey,
        expiresAt,
        model: sessionModel,
        base_instructions: sessionBaseInstructions,
      } = await tokenRes.json()
      if (!ephemeralKey) throw new Error('No ephemeral key returned')

      // Store sessionType for renewal requests and schedule the first renewal.
      sessionTypeRef.current = options.sessionType ?? 'new_patient'
      if (expiresAt) scheduleRenewal(expiresAt)

      // Phase 5 of 2026-05-27 historian upgrade: store the resolved base
      // instructions so pushLocalizerContext can re-serialize BASE_PROMPT +
      // delta and emit session.update on the data channel every 3 turns.
      baseInstructionsRef.current = sessionBaseInstructions ?? ''

      // 2. Create RTCPeerConnection
      const pc = new RTCPeerConnection()
      pcRef.current = pc

      // 3. Set up remote audio playback
      // iOS Safari requires the element to be attached to the DOM for audio
      // to route correctly (including to the phone's speaker). We hide it
      // visually but keep it in the tree.
      const audioEl = document.createElement('audio')
      audioEl.autoplay = true
      audioEl.controls = false
      // @ts-expect-error - playsinline is valid for iOS Safari
      audioEl.playsInline = true
      audioEl.style.display = 'none'
      audioEl.setAttribute('aria-hidden', 'true')
      document.body.appendChild(audioEl)
      audioElRef.current = audioEl

      pc.ontrack = (event) => {
        audioEl.srcObject = event.streams[0]
        // Ensure playback resumes if the browser paused after srcObject change.
        audioEl.play().catch(() => {})
      }

      // 4. Get user mic
      // Explicit constraints give the best behavior when users listen on
      // speakerphone — the mic will suppress the speaker bleed rather than
      // canceling the AI audio outright.
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: {
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: true,
        },
      })
      streamRef.current = stream
      stream.getTracks().forEach(track => pc.addTrack(track, stream))

      // 5. Create data channel for events
      const dc = pc.createDataChannel('oai-events')
      dcRef.current = dc

      dc.onopen = () => {
        // If session.created already arrived before the channel opened,
        // fire the greeting now — otherwise session.created handler does it.
        if (sessionCreatedRef.current) {
          dc.send(JSON.stringify({
            type: 'response.create',
            response: {},
          }))
        }
      }

      dc.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data)
          handleServerEvent(msg)
        } catch {}
      }

      // Detect server-side session teardown (OpenAI Realtime ~8-min max).
      // Without these handlers the connection goes cold and endSession() never
      // runs — leaving the screen frozen with no closing message.
      // endSession owns finalizingRef — handleDrop just calls it directly.
      const handleDrop = (source: string) => {
        if (sessionGenRef.current !== sessionGen) return // stale handler from a previous session
        console.warn(`[useRealtimeSession] connection dropped (${source}) — running graceful end`)
        endSessionRef.current()
      }

      pc.onconnectionstatechange = () => {
        const state = pc.connectionState
        console.log('[useRealtimeSession] pc.connectionState ->', state)
        // Skip 'disconnected' — ICE can bounce disconnected→connected on a brief
        // network blip; only treat terminal states as a real drop.
        if (state === 'failed' || state === 'closed') {
          handleDrop(`pc:${state}`)
        }
      }

      dc.onclose = () => {
        console.log('[useRealtimeSession] data channel closed')
        handleDrop('dc:close')
      }

      // 6. SDP offer
      const offer = await pc.createOffer()
      await pc.setLocalDescription(offer)

      // 7. Send offer to OpenAI, get answer
      // Current GA endpoint per platform.openai.com (2026-05). Model passed as
      // query param. Ephemeral key is the bearer.
      const realtimeModel = sessionModel ?? 'gpt-realtime-2'

      const sdpRes = await fetch(
        `https://api.openai.com/v1/realtime/calls?model=${encodeURIComponent(realtimeModel)}`,
        {
          method: 'POST',
          body: offer.sdp,
          headers: {
            Authorization: `Bearer ${ephemeralKey}`,
            'Content-Type': 'application/sdp',
          },
        },
      )

      if (!sdpRes.ok) {
        const errorBody = await sdpRes.text()
        console.error('[useRealtimeSession] SDP exchange failed:', sdpRes.status, errorBody)
        throw new Error(`OpenAI Realtime SDP exchange returned ${sdpRes.status}: ${errorBody}`)
      }

      const sdpAnswer = await sdpRes.text()
      await pc.setRemoteDescription({ type: 'answer', sdp: sdpAnswer })

      // 8. Start timer
      startTimeRef.current = Date.now()
      timerRef.current = setInterval(() => {
        setDuration(Math.floor((Date.now() - startTimeRef.current) / 1000))
      }, 1000)

      setStatus('active')
    } catch (err: any) {
      console.error('Failed to start realtime session:', err)
      setError(err.message || 'Failed to start session')
      setStatus('error')
      cleanup()
    }
  }, [options.sessionType, options.referralReason, options.patientContext, cleanup])

  // Handle server events from the data channel
  const handleServerEvent = useCallback((msg: any) => {
    switch (msg.type) {
      case 'session.created': {
        // Session is fully configured — instructions are applied. Mark the
        // ref so dc.onopen can fire the greeting if the channel isn't open
        // yet, then fire immediately if it already is.
        sessionCreatedRef.current = true
        if (dcRef.current?.readyState === 'open') {
          dcRef.current.send(JSON.stringify({
            type: 'response.create',
            response: {},
          }))
        }
        break
      }

      case 'response.audio_transcript.delta': {
        // Streaming AI text
        setCurrentAssistantText(prev => prev + (msg.delta || ''))
        setIsAiSpeaking(true)
        break
      }

      case 'response.audio_transcript.done': {
        // AI finished speaking this response
        const fullText = msg.transcript || ''
        if (fullText.trim()) {
          const entry: HistorianTranscriptEntry = {
            role: 'assistant',
            text: fullText.trim(),
            timestamp: Math.floor((Date.now() - startTimeRef.current) / 1000),
          }
          transcriptRef.current = [...transcriptRef.current, entry]
          setTranscript([...transcriptRef.current])
          questionCountRef.current += 1
        }
        setCurrentAssistantText('')
        setIsAiSpeaking(false)

        // If save_interview_output already fired, this audio is the closing
        // message. Schedule auto-end now that the AI has finished speaking —
        // use a ref so this handler never has a stale closure on endSessionRef.
        if (interviewCompletedRef.current && !finalizingRef.current) {
          if (autoEndTimerRef.current) clearTimeout(autoEndTimerRef.current)
          autoEndTimerRef.current = setTimeout(() => {
            endSessionRef.current()
          }, 0)
        }
        break
      }

      case 'conversation.item.input_audio_transcription.completed': {
        // User finished speaking
        const userText = msg.transcript || ''
        if (userText.trim()) {
          const entry: HistorianTranscriptEntry = {
            role: 'user',
            text: userText.trim(),
            timestamp: Math.floor((Date.now() - startTimeRef.current) / 1000),
          }
          transcriptRef.current = [...transcriptRef.current, entry]
          setTranscript([...transcriptRef.current])

          // Safety check on user speech
          checkSafety(userText)

          // Red flag detection: run keyword matching on cumulative transcript
          const fullText = transcriptRef.current
            .filter(t => t.role === 'user')
            .map(t => t.text)
            .join(' ')
          const detection = detectRedFlags(fullText, options.consultId ?? 'ephemeral')
          if (detection.detected_flags.length > 0) {
            setDetectedRedFlags(detection.detected_flags)
            options.onRedFlagDetected?.(detection.detected_flags)
          }

          // Localizer: increment patient turn counter and trigger every 3 turns
          patientTurnCountRef.current += 1
          const turnsSinceLast = patientTurnCountRef.current - lastLocalizerTurnRef.current
          if (turnsSinceLast >= LOCALIZER_INTERVAL) {
            lastLocalizerTurnRef.current = patientTurnCountRef.current
            // Fire async — must not block the event loop
            runLocalizer()
          }
        }
        setCurrentUserText('')
        setIsUserSpeaking(false)
        break
      }

      case 'input_audio_buffer.speech_started': {
        setIsUserSpeaking(true)
        setCurrentUserText('(listening...)')
        break
      }

      case 'input_audio_buffer.speech_stopped': {
        setIsUserSpeaking(false)
        break
      }

      case 'response.done': {
        // Check if the response includes tool calls
        const output = msg.response?.output
        if (output && Array.isArray(output)) {
          for (const item of output) {
            if (item.type !== 'function_call') continue

            // ── save_interview_output (existing) ──
            if (item.name === 'save_interview_output') {
              try {
                const args = JSON.parse(item.arguments || '{}')
                const { narrative_summary, red_flags, safety_escalated, ...structured } = args
                structuredOutputRef.current = structured
                narrativeSummaryRef.current = narrative_summary || null
                if (red_flags && Array.isArray(red_flags)) {
                  redFlagsRef.current = red_flags
                }
                if (safety_escalated) {
                  safetyEscalatedRef.current = true
                }
                // Signal to consumers that the interview has concluded so
                // they can auto-end the session after the AI's closing line.
                setInterviewCompleted(true)

                if (dcRef.current?.readyState === 'open') {
                  dcRef.current.send(JSON.stringify({
                    type: 'conversation.item.create',
                    item: {
                      type: 'function_call_output',
                      call_id: item.call_id,
                      output: JSON.stringify({ success: true }),
                    },
                  }))
                  dcRef.current.send(JSON.stringify({
                    type: 'response.create',
                    response: {},
                  }))
                }
              } catch (e) {
                console.error('Error parsing save_interview_output:', e)
              }
            }

            // ── save_scale_responses (Phase 3) ──
            if (item.name === 'save_scale_responses') {
              try {
                const args: SaveScaleResponsesArgs = JSON.parse(item.arguments || '{}')

                // Track which scales have been administered this session
                const updatedSet = new Set(administeredScaleIdsRef.current)
                updatedSet.add(args.scale_id)
                administeredScaleIdsRef.current = updatedSet
                setAdministeredScaleIds(new Set(updatedSet))

                // Notify parent so it can POST to /api/ai/historian/scales?action=submit
                onScaleCompleteRef.current?.(args)

                // Acknowledge so model can continue the intake interview
                if (dcRef.current?.readyState === 'open') {
                  dcRef.current.send(JSON.stringify({
                    type: 'conversation.item.create',
                    item: {
                      type: 'function_call_output',
                      call_id: item.call_id,
                      output: JSON.stringify({ success: true, recorded: args.scale_id }),
                    },
                  }))
                  dcRef.current.send(JSON.stringify({
                    type: 'response.create',
                    response: {},
                  }))
                }
              } catch (e) {
                console.error('Error parsing save_scale_responses:', e)
              }
            }

            // ── scale_step (Phase 4 — paginated single-item admin) ──
            // Replaces the legacy save_scale_responses tool. Each call returns
            // exactly one scale item from the server; the model recites it
            // verbatim, awaits patient response, then calls scale_step again
            // with prev_response. Final call returns {done:true, total_score, ...}.
            if (item.name === 'scale_step') {
              ;(async () => {
                try {
                  const args = JSON.parse(item.arguments || '{}')
                  const res = await fetch('/api/ai/historian/scales?action=step', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                      scale_id: args.scale_id,
                      reason: args.reason,
                      prev_index: args.prev_index,
                      prev_response: args.prev_response,
                      // consult_id is the session-scope key for in-progress
                      // scale_results lookups. historian_session_id has a strict
                      // FK to historian_sessions and is populated server-side
                      // when the in-progress row gets backfilled.
                      consult_id: options.consultId ?? undefined,
                    }),
                  })
                  const result = await res.json()

                  // If the scale just completed, mark it administered and
                  // notify the parent (replaces the old save_scale_responses
                  // notify path).
                  if (result?.done === true && typeof args.scale_id === 'string') {
                    const updatedSet = new Set(administeredScaleIdsRef.current)
                    updatedSet.add(args.scale_id)
                    administeredScaleIdsRef.current = updatedSet
                    setAdministeredScaleIds(new Set(updatedSet))
                    onScaleCompleteRef.current?.({
                      scale_id: args.scale_id,
                      responses: {}, // raw_responses live server-side now
                      total_score: result.total_score,
                      interpretation: result.interpretation,
                      severity_level: result.severity_level,
                    } as any)
                  }

                  if (dcRef.current?.readyState === 'open') {
                    dcRef.current.send(
                      JSON.stringify({
                        type: 'conversation.item.create',
                        item: {
                          type: 'function_call_output',
                          call_id: item.call_id,
                          output: JSON.stringify(result),
                        },
                      }),
                    )
                    dcRef.current.send(JSON.stringify({ type: 'response.create' }))
                  }
                } catch (err) {
                  console.error('[useRealtimeSession] scale_step handler error:', err)
                  if (dcRef.current?.readyState === 'open') {
                    dcRef.current.send(
                      JSON.stringify({
                        type: 'conversation.item.create',
                        item: {
                          type: 'function_call_output',
                          call_id: item.call_id,
                          output: JSON.stringify({ status: 'error', message: 'client error' }),
                        },
                      }),
                    )
                    dcRef.current.send(JSON.stringify({ type: 'response.create' }))
                  }
                }
              })()
            }

            // ── query_evidence (Phase 3) ──
            if (item.name === 'query_evidence') {
              // handleServerEvent is sync; run fetch in a fire-and-forget async IIFE
              ;(async () => {
                try {
                  const args = JSON.parse(item.arguments || '{}')
                  const res = await fetch('/api/ai/historian/evidence-query', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                      question: args.question,
                      focus_diagnoses: args.focus_diagnoses,
                    }),
                  })
                  const result = await res.json()

                  if (dcRef.current?.readyState === 'open') {
                    // Send the tool result back to the model over the data channel
                    dcRef.current.send(
                      JSON.stringify({
                        type: 'conversation.item.create',
                        item: {
                          type: 'function_call_output',
                          call_id: item.call_id,
                          output: JSON.stringify(result),
                        },
                      }),
                    )
                    // Prompt the model to continue speaking
                    dcRef.current.send(JSON.stringify({ type: 'response.create' }))
                  }
                } catch (err) {
                  console.error('[useRealtimeSession] query_evidence handler error:', err)
                  if (dcRef.current?.readyState === 'open') {
                    dcRef.current.send(
                      JSON.stringify({
                        type: 'conversation.item.create',
                        item: {
                          type: 'function_call_output',
                          call_id: item.call_id,
                          output: JSON.stringify({ status: 'error', chunks: [], message: 'client error' }),
                        },
                      }),
                    )
                    dcRef.current.send(JSON.stringify({ type: 'response.create' }))
                  }
                }
              })()
            }
          }
        }
        break
      }

      case 'error': {
        console.error('Realtime API error:', msg.error)
        setError(msg.error?.message || 'Realtime API error')
        break
      }
    }
  }, [checkSafety, runLocalizer])

  /**
   * Injects scale administration instructions into the live session.
   * Sends a session.update event to update the model's system prompt,
   * then triggers a new AI response to begin asking scale questions.
   *
   * @param instructionBlock - The instruction text built by buildScaleAdministrationInstructions()
   */
  /**
   * Phase 5 of 2026-05-27 historian upgrade — Localizer push channel.
   *
   * Called after each Localizer pipeline run completes (every ~3 turns).
   * Re-serializes BASE_PROMPT + latest delta into the full instructions
   * string and emits session.update on the data channel.
   *
   * Why this pattern (vs conversation.item.create with a role:"system"
   * message): see spec section 4 + Cross-check round 2.
   *   - session.update OVERWRITES the instructions field — by passing the
   *     full re-serialized BASE + delta, we preserve the base prompt + safety
   *     block (no loss) AND keep only the latest delta active (no timeline
   *     pollution from accumulating role:"system" messages).
   *
   * Non-fatal: if the push fails, the interview continues on the prior
   * instructions. No retries.
   */
  const pushLocalizerContext = useCallback(
    (pushPayload: {
      top_differentials?: string[]
      suggested_next_question?: string | null
      suggested_scale_id?: string | null
      turn_count?: number
    }) => {
      if (dcRef.current?.readyState !== 'open') return
      if (!baseInstructionsRef.current) return

      const delta = [
        `[LATEST LOCALIZER PUSH${pushPayload.turn_count != null ? ` @ turn ${pushPayload.turn_count}` : ''}]`,
        `- Top differentials: ${(pushPayload.top_differentials ?? []).join(', ') || '(none yet)'}`,
        `- Suggested next question: ${pushPayload.suggested_next_question ?? '(none)'}`,
        `- Suggested scale to consider: ${pushPayload.suggested_scale_id ?? '(none)'}`,
      ].join('\n')

      const updatedInstructions = baseInstructionsRef.current + '\n\n' + delta

      try {
        dcRef.current.send(
          JSON.stringify({
            type: 'session.update',
            session: {
              // OpenAI's new Realtime API requires session.type on every
              // session.update, not just at session create. Without it the
              // push gets rejected with HTTP 400 missing_required_parameter.
              // Caught by /tmp/historian-play.py WSS smoke 2026-05-27.
              type: 'realtime',
              instructions: updatedInstructions,
            },
          }),
        )
      } catch (err) {
        console.error('[useRealtimeSession] pushLocalizerContext failed:', err)
        // Non-fatal — interview continues on previous instructions
      }
    },
    [],
  )

  const injectScaleAdministration = useCallback((instructionBlock: string) => {
    if (dcRef.current?.readyState !== 'open') {
      console.warn('[useRealtimeSession] injectScaleAdministration: data channel not open')
      return
    }
    // Append the scale block to the current session instructions
    dcRef.current.send(JSON.stringify({
      type: 'session.update',
      session: {
        // The Realtime API appends this to the model's system context.
        // We set instructions to undefined so we only pass the delta.
        // In practice, we inject via a user-turn message to avoid clobbering the full prompt.
      },
    }))
    // Inject as a system message in the conversation context
    dcRef.current.send(JSON.stringify({
      type: 'conversation.item.create',
      item: {
        type: 'message',
        role: 'user',
        content: [
          {
            type: 'input_text',
            text: `[SYSTEM INSTRUCTION — SCALE ADMINISTRATION]\n${instructionBlock}\n[END SYSTEM INSTRUCTION]`,
          },
        ],
      },
    }))
    // Trigger the model to start asking scale questions
    dcRef.current.send(JSON.stringify({
      type: 'response.create',
      response: {},
    }))
  }, [])

  const endSession = useCallback(async () => {
    if (finalizingRef.current) return
    finalizingRef.current = true
    setStatus('ending')

    const finalDuration = Math.floor((Date.now() - startTimeRef.current) / 1000)
    setDuration(finalDuration)

    // If the AI never called save_interview_output but the patient has had a
    // real conversation, nudge it to save before we tear down the WebRTC
    // connection. Without this, ending early (manual "End Interview" click)
    // silently drops the entire intake — both the structured output and the
    // narrative summary — and the review step shows "No interview data
    // available" despite the patient answering questions.
    const needsFlush =
      !structuredOutputRef.current &&
      transcriptRef.current.length >= 2 &&
      dcRef.current?.readyState === 'open'

    if (needsFlush) {
      try {
        dcRef.current!.send(JSON.stringify({
          type: 'conversation.item.create',
          item: {
            type: 'message',
            role: 'system',
            content: [{
              type: 'input_text',
              text: 'The patient has ended the interview early. Immediately call the save_interview_output tool with whatever information has been gathered so far. Populate narrative_summary with a concise summary of the conversation. Do not ask any more questions and do not speak — just call the tool.',
            }],
          },
        }))
        dcRef.current!.send(JSON.stringify({
          type: 'response.create',
          response: { modalities: ['text'] },
        }))

        const deadline = Date.now() + 4000
        while (!structuredOutputRef.current && Date.now() < deadline) {
          await new Promise(r => setTimeout(r, 100))
        }
      } catch (err) {
        console.warn('[useRealtimeSession] flush save prompt failed:', err)
      }
    }

    // Last-resort fallback: if the AI still hasn't produced a narrative (tool
    // didn't fire, channel dropped, model refused, etc.), preserve the raw
    // transcript as the narrative summary so the physician can still see what
    // the patient said.
    if (!narrativeSummaryRef.current && transcriptRef.current.length > 0) {
      const hasPatientSpeech = transcriptRef.current.some(
        t => t.role === 'user' && t.text.trim().length > 0,
      )
      if (hasPatientSpeech) {
        narrativeSummaryRef.current =
          'Interview ended before AI generated a structured summary. Raw transcript:\n\n' +
          transcriptRef.current
            .map(t => `${t.role === 'assistant' ? 'AI' : 'Patient'}: ${t.text}`)
            .join('\n\n')
      }
    }

    cleanup()

    // `interviewCompleted` flips to true only when the AI called
    // save_interview_output. If it never fired, the patient ended before the
    // AI judged the intake complete — flag it as partial.
    const endedEarly = !interviewCompleted

    options.onComplete?.({
      structuredOutput: structuredOutputRef.current,
      narrativeSummary: narrativeSummaryRef.current,
      redFlags: redFlagsRef.current,
      safetyEscalated: safetyEscalatedRef.current,
      transcript: transcriptRef.current,
      duration: finalDuration,
      questionCount: questionCountRef.current,
      endedEarly,
    })

    setStatus('complete')
  }, [cleanup, options, interviewCompleted])

  // Keep the ref in sync so startSession's drop handlers always call the latest endSession.
  useEffect(() => { endSessionRef.current = endSession }, [endSession])

  // Clean up on unmount
  useEffect(() => {
    return () => {
      cleanup()
    }
  }, [cleanup])

  return {
    status,
    transcript,
    currentAssistantText,
    currentUserText,
    isAiSpeaking,
    isUserSpeaking,
    duration,
    error,
    localizerData,
    localizerLoading,
    startSession,
    endSession,
    injectScaleAdministration,
    pushLocalizerContext,
    administeredScaleIds,
    detectedRedFlags,
    interviewCompleted,
  }
}
