// ──────────────────────────────────────────────────────────────────────────────
// Demo Patient Schedule Data — 18 morning patients across 3 providers
// Snapshot: 2026-02-26 ~9:40 AM
// Used by MA Dashboard (flow board) and Practice Manager Dashboard (metrics)
// ──────────────────────────────────────────────────────────────────────────────

import type { PatientScheduleItem } from './types'

export const DEMO_PATIENTS: PatientScheduleItem[] = [
  // ── Dr. Chen (7 patients) ──────────────────────────────────────────────────

  {
    id: 'pt-martinez',
    name: 'Linda Martinez',
    age: 58,
    sex: 'F',
    primary_diagnosis: 'Parkinson\'s Disease',
    appointment_time: '2026-02-26T08:00:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-chen',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'completed',
    ai_readiness: {
      historian_status: 'imported',
      sdne_status: 'completed',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Parkinson\'s follow-up, wearable shows increased falls',
  },

  {
    id: 'pt-wright',
    name: 'Thomas Wright',
    age: 71,
    sex: 'M',
    primary_diagnosis: 'Epilepsy',
    appointment_time: '2026-02-26T08:30:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-chen',
    location: 'clinic',
    clinic_site_id: 'site-lakewood',
    flow_stage: 'completed',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Epilepsy medication check',
  },

  {
    id: 'pt-delgado',
    name: 'Carlos Delgado',
    age: 58,
    sex: 'M',
    primary_diagnosis: 'Suspected GBS',
    appointment_time: '2026-02-26T09:00:00',
    appointment_duration: 60,
    visit_type: 'urgent',
    provider_id: 'prov-chen',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'no_show',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Progressive leg weakness — rule out GBS',
  },

  {
    id: 'pt-santos',
    name: 'Maria Santos',
    age: 34,
    sex: 'F',
    primary_diagnosis: 'Chronic Migraine',
    appointment_time: '2026-02-26T09:30:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-chen',
    location: 'home',
    clinic_site_id: null,
    flow_stage: 'checked_in',
    ai_readiness: {
      historian_status: 'sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: false,
    video_link_active: false,
    chief_complaint: 'Migraine referral — chronic daily headache',
  },

  {
    id: 'pt-jennings',
    name: 'Harold Jennings',
    age: 74,
    sex: 'M',
    primary_diagnosis: 'Possible Parkinsonism',
    appointment_time: '2026-02-26T10:00:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-chen',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'New tremor and gait difficulty — possible parkinsonism',
  },

  {
    id: 'pt-price',
    name: 'Angela Price',
    age: 45,
    sex: 'F',
    primary_diagnosis: 'Multiple Sclerosis',
    appointment_time: '2026-02-26T10:30:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-chen',
    location: 'home',
    clinic_site_id: null,
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: false,
    video_link_active: false,
    chief_complaint: 'MS follow-up',
  },

  {
    id: 'pt-torres',
    name: 'William Torres',
    age: 62,
    sex: 'M',
    primary_diagnosis: 'Neuropathy',
    appointment_time: '2026-02-26T11:00:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-chen',
    location: 'clinic',
    clinic_site_id: 'site-lakewood',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Neuropathy routine follow-up',
  },

  // ── Dr. Patel (7 patients) ─────────────────────────────────────────────────

  {
    id: 'pt-dchen',
    name: 'Dorothy Chen',
    age: 72,
    sex: 'F',
    primary_diagnosis: 'Memory Loss',
    appointment_time: '2026-02-26T08:00:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-patel',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'completed',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Memory follow-up — insurance denied donepezil',
  },

  {
    id: 'pt-brown',
    name: 'Keisha Brown',
    age: 28,
    sex: 'F',
    primary_diagnosis: 'Epilepsy',
    appointment_time: '2026-02-26T08:30:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-patel',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'post_visit',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Epilepsy follow-up — Keppra side effects',
  },

  {
    id: 'pt-kim',
    name: 'Robert Kim',
    age: 48,
    sex: 'M',
    primary_diagnosis: 'Headache',
    appointment_time: '2026-02-26T09:00:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-patel',
    location: 'clinic',
    clinic_site_id: 'site-lakewood',
    flow_stage: 'vitals_done',
    ai_readiness: {
      historian_status: 'imported',
      sdne_status: 'completed',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: true,
    chief_complaint: 'New patient headache evaluation — gold standard AI prep',
  },

  {
    id: 'pt-voss',
    name: 'Eleanor Voss',
    age: 66,
    sex: 'F',
    primary_diagnosis: 'New Tremor',
    appointment_time: '2026-02-26T09:30:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-patel',
    location: 'home',
    clinic_site_id: null,
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: false,
    video_link_active: false,
    chief_complaint: 'New tremor — needs historian reminder',
  },

  {
    id: 'pt-liu',
    name: 'James Liu',
    age: 55,
    sex: 'M',
    primary_diagnosis: 'Migraine',
    appointment_time: '2026-02-26T10:00:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-patel',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Migraine follow-up',
  },

  {
    id: 'pt-moore',
    name: 'Patricia Moore',
    age: 39,
    sex: 'F',
    primary_diagnosis: 'Epilepsy',
    appointment_time: '2026-02-26T10:30:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-patel',
    location: 'clinic',
    clinic_site_id: 'site-lakewood',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Epilepsy follow-up — no pre-visit data',
  },

  {
    id: 'pt-nguyen',
    name: 'David Nguyen',
    age: 44,
    sex: 'M',
    primary_diagnosis: 'Sleep Disorder',
    appointment_time: '2026-02-26T11:00:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-patel',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Sleep disorder referral',
  },

  // ── Dr. Rivera (7 patients, one cancelled) ─────────────────────────────────

  {
    id: 'pt-williams',
    name: 'Sandra Williams',
    age: 41,
    sex: 'F',
    primary_diagnosis: 'Multiple Sclerosis',
    appointment_time: '2026-02-26T08:00:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-rivera',
    location: 'clinic',
    clinic_site_id: 'site-lakewood',
    flow_stage: 'completed',
    ai_readiness: {
      historian_status: 'imported',
      sdne_status: 'completed',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'MS follow-up — routine, went well',
  },

  {
    id: 'pt-cancelled',
    name: 'Cancelled',
    age: 0,
    sex: 'M',
    primary_diagnosis: '',
    appointment_time: '2026-02-26T08:30:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-rivera',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'cancelled',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: false,
    video_link_active: false,
    chief_complaint: 'Cancelled appointment',
  },

  {
    id: 'pt-okonkwo',
    name: 'James Okonkwo',
    age: 42,
    sex: 'M',
    primary_diagnosis: 'Post-seizure evaluation',
    appointment_time: '2026-02-26T09:00:00',
    appointment_duration: 60,
    visit_type: 'follow_up',
    provider_id: 'prov-rivera',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'in_visit',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: true,
    chief_complaint: 'Post-seizure follow-up — complex, running over +8 min',
  },

  {
    id: 'pt-dongyue',
    name: 'Chen Dongyue',
    age: 37,
    sex: 'M',
    primary_diagnosis: 'Suspected MS',
    appointment_time: '2026-02-26T09:30:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-rivera',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'vitals_done',
    ai_readiness: {
      historian_status: 'imported',
      sdne_status: 'completed',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'New MS referral — fully prepped, waiting',
  },

  {
    id: 'pt-alvarez',
    name: 'Robert Alvarez',
    age: 55,
    sex: 'M',
    primary_diagnosis: 'MS + Depression',
    appointment_time: '2026-02-26T10:00:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-rivera',
    location: 'home',
    clinic_site_id: null,
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'completed',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: false,
    video_link_active: false,
    chief_complaint: 'MS follow-up — safety flag for depression',
  },

  {
    id: 'pt-mkim',
    name: 'Margaret Kim',
    age: 60,
    sex: 'F',
    primary_diagnosis: 'NMO',
    appointment_time: '2026-02-26T10:30:00',
    appointment_duration: 30,
    visit_type: 'follow_up',
    provider_id: 'prov-rivera',
    location: 'clinic',
    clinic_site_id: 'site-lakewood',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'ready',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'NMO follow-up — infusion discussion',
  },

  {
    id: 'pt-park',
    name: 'Lisa Park',
    age: 32,
    sex: 'F',
    primary_diagnosis: 'Possible MS',
    appointment_time: '2026-02-26T11:00:00',
    appointment_duration: 60,
    visit_type: 'new',
    provider_id: 'prov-rivera',
    location: 'clinic',
    clinic_site_id: 'site-riverview',
    flow_stage: 'not_arrived',
    ai_readiness: {
      historian_status: 'not_sent',
      sdne_status: 'not_applicable',
      chart_prep_status: 'not_started',
    },
    local_ma_assigned: true,
    video_link_active: false,
    chief_complaint: 'Possible MS — new referral, no pre-visit data',
  },
]

// ── Helper functions ──────────────────────────────────────────────────────────

export function getPatientsByProvider(providerId: string): PatientScheduleItem[] {
  return DEMO_PATIENTS.filter(p => p.provider_id === providerId)
}

export function getPatientsBySite(siteId: string): PatientScheduleItem[] {
  if (siteId === 'site-home') {
    return DEMO_PATIENTS.filter(p => p.location === 'home')
  }
  return DEMO_PATIENTS.filter(p => p.clinic_site_id === siteId)
}
